import type { DynamixCinematicContract } from "./dynamix-cinematic-types.js";
import { dynamixAction, dynamixTiming, dynamixVisual } from "./dynamix-cinematic-preset-helpers.js";

export const deadChannelDynamixContract: DynamixCinematicContract = {
  contractVersion: 1,
  id: "dead-channel",
  label: "Dead Channel clock-driven cyber-noir",
  summary:
    "Original urban investigation with a visible case clock, scheduled contacts, compact location " +
    "cuts, evidence-gated choices and recoverable first-person action inserts.",
  productionProfileId: "cinematic-pulp-vga",
  originalProofTitle: "Dead Channel",
  originalAssetsOnly: true,
  visual: dynamixVisual(
    "Dark full-screen urban rooms, close evidence inserts, contact portraits and a small " +
      "persistent case clock.",
    [
      "Compose city locations from hard value blocks, wet-surface accents and one evidence colour.",
      "Keep the clock legible but visually subordinate to faces, hands and active evidence.",
      "Use apartment, transit, office and danger-location cuts with consistent screen geography.",
      "Avoid generic cyberpunk neon; every colour accent must identify evidence, access or threat.",
    ],
    [
      "Use six to eight walk frames and two-frame idle changes in ordinary rooms.",
      "Use two to three portrait expressions with strong eyeline changes rather than smooth lip motion.",
      "Telegraph action windows through silhouette, sound cue and held anticipation pose.",
      "Use tight cuts, short holds and explicit failure panels; never derive outcomes from render cadence.",
    ],
  ),
  timing: dynamixTiming("continuous", 300, {
    pointerAcknowledgeTicks: 0,
    hotspotCommitTicks: 2,
    portraitRevealTicks: 10,
    dialogueMinimumTicks: 78,
    locationCutTicks: 10,
    montagePanelTicks: 30,
    actionTelegraphTicks: 12,
    actionRecoveryTicks: 18,
    failureHoldTicks: 42,
  }),
  start: {
    day: 3,
    hour: 19,
    minute: 0,
    locationId: "dead-channel.apartment",
    protagonistId: "dead-channel.investigator",
  },
  protagonists: [
    {
      id: "dead-channel.investigator",
      name: "Lena Marr",
      knowledgeFlags: ["dead-channel.case-open", "dead-channel.signal-known"],
      inventoryIds: ["dead-channel.recorder", "dead-channel.transit-card"],
      portraitDirection: "Hard side light, restrained expression and one evidence-colour reflection.",
      movementDirection: "Compact coat silhouette with quick stops and deliberate evidence handling.",
    },
  ],
  relationships: [
    {
      id: "dead-channel.contact-trust",
      label: "Contact trust",
      initialValue: 40,
      minimum: 0,
      maximum: 100,
      visibleLabels: [
        { maximumValue: 24, label: "afraid" },
        { maximumValue: 49, label: "guarded" },
        { maximumValue: 74, label: "cooperative" },
        { maximumValue: 100, label: "committed" },
      ],
    },
  ],
  routes: [
    {
      id: "dead-channel.route.transit-office",
      label: "Transit records office",
      fromLocationId: "dead-channel.apartment",
      toLocationId: "dead-channel.transit-office",
      allowedProtagonistIds: ["dead-channel.investigator"],
      costMinutes: 18,
      requiredFlags: [],
      setFlags: ["dead-channel.transit-office-visited"],
      relationshipChanges: {},
      montagePanels: [
        "Case clock insert",
        "Rain platform",
        "Records-office doorway",
      ],
      consequence: "The records office opens a timetable lead while advancing the visible case clock.",
    },
    {
      id: "dead-channel.route.night-market",
      label: "Night-market contact",
      fromLocationId: "dead-channel.transit-office",
      toLocationId: "dead-channel.night-market",
      allowedProtagonistIds: ["dead-channel.investigator"],
      costMinutes: 22,
      requiredFlags: ["dead-channel.timetable-found"],
      setFlags: ["dead-channel.contact-reached"],
      relationshipChanges: { "dead-channel.contact-trust": 4 },
      montagePanels: [
        "Timetable close-up",
        "Elevated train",
        "Market awning",
      ],
      consequence: "The contact can be reached only before the scheduled departure window closes.",
    },
    {
      id: "dead-channel.route.transmitter",
      label: "Service-tower transmitter",
      fromLocationId: "dead-channel.night-market",
      toLocationId: "dead-channel.service-tower",
      allowedProtagonistIds: ["dead-channel.investigator"],
      costMinutes: 16,
      requiredFlags: ["dead-channel.tower-location-known"],
      setFlags: ["dead-channel.service-tower-entered"],
      relationshipChanges: {},
      montagePanels: [
        "Clock warning",
        "Service lift",
        "Transmitter corridor",
      ],
      consequence: "The final danger location opens with only the remaining case time available.",
    },
  ],
  choices: [
    {
      id: "dead-channel.choice.copy-timetable",
      label: "Copy the restricted timetable",
      requiredFlags: ["dead-channel.transit-office-visited"],
      setFlags: ["dead-channel.timetable-found"],
      relationshipChanges: {},
      timeCostMinutes: 7,
      consequence: "A scheduled contact window becomes visible on the case clock.",
    },
    {
      id: "dead-channel.choice.share-evidence",
      label: "Share the signal recording",
      requiredFlags: ["dead-channel.contact-reached"],
      setFlags: ["dead-channel.tower-location-known"],
      relationshipChanges: { "dead-channel.contact-trust": 16 },
      timeCostMinutes: 9,
      consequence: "The contact identifies the transmitter and agrees to hold the service lift.",
    },
    {
      id: "dead-channel.choice.press-contact",
      label: "Pressure the contact",
      requiredFlags: ["dead-channel.contact-reached"],
      setFlags: ["dead-channel.tower-location-known", "dead-channel.contact-pressured"],
      relationshipChanges: { "dead-channel.contact-trust": -30 },
      timeCostMinutes: 3,
      consequence: "The tower opens faster, but no help remains after an action failure.",
    },
  ],
  actions: [
    dynamixAction({
      id: "dead-channel.action.fire-escape",
      label: "Service-tower fire escape",
      kind: "escape",
      locationId: "dead-channel.service-tower",
      durationTicks: 132,
      safeAnchorId: "dead-channel.anchor.fire-escape",
      windows: [
        {
          id: "dead-channel.action.fire-escape.brace",
          opensAtTick: 16,
          closesAtTick: 36,
          input: "guard",
          telegraph: "The ladder shudders before the first impact.",
          successBeat: "The investigator braces against the wall.",
        },
        {
          id: "dead-channel.action.fire-escape.climb",
          opensAtTick: 52,
          closesAtTick: 78,
          input: "up",
          telegraph: "The upper landing clears behind a moving searchlight.",
          successBeat: "A two-step climb reaches the shadowed landing.",
        },
        {
          id: "dead-channel.action.fire-escape.enter",
          opensAtTick: 92,
          closesAtTick: 118,
          input: "act",
          telegraph: "The service hatch releases on one audible click.",
          successBeat: "The hatch opens before the patrol returns.",
        },
      ],
      timeCostMinutes: 6,
      successFlags: [
        "dead-channel.fire-escape-cleared",
        "dead-channel.transmitter-secured",
      ],
      failureFlags: ["dead-channel.fire-escape-failed"],
      successRelationshipChanges: { "dead-channel.contact-trust": 4 },
      failureRelationshipChanges: { "dead-channel.contact-trust": -5 },
      successConsequence: "The transmitter is secured before its final scheduled broadcast.",
      failureConsequence: "The scene returns to the ladder anchor with the case clock and evidence intact.",
    }),
  ],
  deadlines: [
    {
      id: "dead-channel.deadline.contact",
      gameMinute: 3 * 24 * 60 + 20 * 60 + 15,
      requiredFlag: "dead-channel.contact-reached",
      failureOutcomeId: "dead-channel.outcome.contact-lost",
      warningMinutes: [30, 15, 5],
    },
    {
      id: "dead-channel.deadline.broadcast",
      gameMinute: 3 * 24 * 60 + 21 * 60 + 30,
      requiredFlag: "dead-channel.transmitter-secured",
      failureOutcomeId: "dead-channel.outcome.broadcast",
      warningMinutes: [45, 20, 5],
    },
  ],
  outcomes: [
    {
      id: "dead-channel.outcome.signal-stopped",
      kind: "success",
      title: "SIGNAL STOPPED",
      message: "The transmitter is secured and the contact survives the case window.",
      requiredFlags: ["dead-channel.transmitter-secured"],
      minimumRelationships: { "dead-channel.contact-trust": 25 },
    },
    {
      id: "dead-channel.outcome.silent-victory",
      kind: "success",
      title: "CHANNEL CLOSED",
      message: "The transmitter is stopped, but the contact disappears before the report is filed.",
      requiredFlags: ["dead-channel.transmitter-secured"],
      minimumRelationships: { "dead-channel.contact-trust": 0 },
    },
    {
      id: "dead-channel.outcome.contact-lost",
      kind: "failure",
      title: "CONTACT LOST",
      message: "The scheduled witness leaves before the investigator reaches the night market.",
      requiredFlags: [],
      minimumRelationships: {},
    },
    {
      id: "dead-channel.outcome.broadcast",
      kind: "failure",
      title: "THE BROADCAST BEGINS",
      message: "The case clock reaches the final transmission before the tower is secured.",
      requiredFlags: [],
      minimumRelationships: {},
    },
  ],
  designRules: [
    "The visible clock advances through continuous play and explicit travel, dialogue and action costs.",
    "Every scheduled contact window must be legible before it closes and produce a distinct recovery path.",
    "Evidence changes available dialogue and locations rather than only adding hidden flags.",
    "Action failure restores the authored safe anchor while preserving clock, evidence and " +
      "relationship state.",
  ],
};
