import type { DynamixCinematicContract } from "./dynamix-cinematic-types.js";
import { dynamixAction, dynamixTiming, dynamixVisual } from "./dynamix-cinematic-preset-helpers.js";

export const jadeHorizonDynamixContract: DynamixCinematicContract = {
  contractVersion: 1,
  id: "jade-horizon",
  label: "Jade Horizon editorial travel thriller",
  summary:
    "Original cinematic travel adventure with two protagonists, costed routes, relationship " +
    "consequences, hard editorial panels and recoverable action inserts.",
  productionProfileId: "cinematic-pulp-vga",
  originalProofTitle: "Jade Horizon",
  originalAssetsOnly: true,
  visual: dynamixVisual(
    "Painted full-screen locations, framed portrait exchanges, map-room inserts and hard editorial cuts.",
    [
      "Build each location from five to seven large value groups before material detail.",
      "Reserve faces, hands, route evidence and danger accents from the room palette.",
      "Treat travel montages as authored panels with geographic continuity, not loading screens.",
      "Review native pixels and the intended four-by-three DOS presentation together.",
    ],
    [
      "Use six to ten walk frames with explicit start, turn and stop poses.",
      "Use two to four portrait expression frames and hold them long enough to read subtext.",
      "Build action inserts from anticipation, committed pose, impact and recovery.",
      "Use palette steps, hard cuts and held panels instead of modern interpolation.",
    ],
  ),
  timing: dynamixTiming("costed-only", 0, {
    pointerAcknowledgeTicks: 1,
    hotspotCommitTicks: 3,
    portraitRevealTicks: 14,
    dialogueMinimumTicks: 102,
    locationCutTicks: 16,
    montagePanelTicks: 48,
    actionTelegraphTicks: 18,
    actionRecoveryTicks: 24,
    failureHoldTicks: 54,
  }),
  start: {
    day: 1,
    hour: 7,
    minute: 30,
    locationId: "jade-horizon.airstrip-office",
    protagonistId: "jade-horizon.courier",
  },
  protagonists: [
    {
      id: "jade-horizon.courier",
      name: "Mara Vey",
      knowledgeFlags: ["jade-horizon.debt-known", "jade-horizon.route-contract-known"],
      inventoryIds: ["jade-horizon.contract", "jade-horizon.field-radio"],
      portraitDirection: "Guarded three-quarter portrait with one warm eye-light.",
      movementDirection: "Economical forward posture with a readable satchel silhouette.",
    },
    {
      id: "jade-horizon.pilot",
      name: "Tomas Rook",
      knowledgeFlags: ["jade-horizon.aircraft-fault-known", "jade-horizon.old-route-known"],
      inventoryIds: ["jade-horizon.flight-key", "jade-horizon.grease-pencil"],
      portraitDirection: "Weathered side-lit portrait with restrained reaction frames.",
      movementDirection: "Broader stance and deliberate equipment-handling poses.",
    },
  ],
  relationships: [
    {
      id: "jade-horizon.trust",
      label: "Trust",
      initialValue: 45,
      minimum: 0,
      maximum: 100,
      visibleLabels: [
        { maximumValue: 24, label: "hostile" },
        { maximumValue: 49, label: "guarded" },
        { maximumValue: 74, label: "working" },
        { maximumValue: 100, label: "loyal" },
      ],
    },
    {
      id: "jade-horizon.fatigue",
      label: "Fatigue",
      initialValue: 10,
      minimum: 0,
      maximum: 100,
      visibleLabels: [
        { maximumValue: 24, label: "fresh" },
        { maximumValue: 54, label: "tired" },
        { maximumValue: 79, label: "strained" },
        { maximumValue: 100, label: "spent" },
      ],
    },
  ],
  routes: [
    {
      id: "jade-horizon.route.river",
      label: "River freight route",
      fromLocationId: "jade-horizon.airstrip-office",
      toLocationId: "jade-horizon.river-hotel",
      allowedProtagonistIds: ["jade-horizon.courier", "jade-horizon.pilot"],
      costMinutes: 210,
      requiredFlags: [],
      setFlags: ["jade-horizon.river-route-taken"],
      relationshipChanges: {
        "jade-horizon.trust": 6,
        "jade-horizon.fatigue": 12,
      },
      montagePanels: [
        "Cargo manifest close-up",
        "Rain-dark river launch",
        "Hotel quay arrival",
      ],
      consequence: "The slower route improves cooperation but leaves less time for the railway.",
    },
    {
      id: "jade-horizon.route.mountain",
      label: "Mountain airstrip route",
      fromLocationId: "jade-horizon.airstrip-office",
      toLocationId: "jade-horizon.cliff-railway",
      allowedProtagonistIds: ["jade-horizon.pilot"],
      costMinutes: 95,
      requiredFlags: ["jade-horizon.flight-key-ready"],
      setFlags: ["jade-horizon.mountain-route-taken"],
      relationshipChanges: {
        "jade-horizon.trust": -8,
        "jade-horizon.fatigue": 20,
      },
      montagePanels: [
        "Engine-start insert",
        "Cloud-wall silhouette",
        "Cliff railway approach",
      ],
      consequence: "The route preserves time but exposes the pilot's concealed aircraft fault.",
    },
    {
      id: "jade-horizon.route.night-train",
      label: "Night train route",
      fromLocationId: "jade-horizon.river-hotel",
      toLocationId: "jade-horizon.cliff-railway",
      allowedProtagonistIds: ["jade-horizon.courier", "jade-horizon.pilot"],
      costMinutes: 155,
      requiredFlags: ["jade-horizon.train-passage-secured"],
      setFlags: ["jade-horizon.train-route-taken"],
      relationshipChanges: {
        "jade-horizon.trust": 4,
        "jade-horizon.fatigue": 18,
      },
      montagePanels: [
        "Platform negotiation",
        "Carriage corridor",
        "Dawn bridge reveal",
      ],
      consequence: "The shared journey exposes different knowledge to each protagonist.",
    },
  ],
  choices: [
    {
      id: "jade-horizon.choice.share-fault",
      label: "Disclose the aircraft fault",
      requiredFlags: ["jade-horizon.aircraft-fault-known"],
      setFlags: ["jade-horizon.fault-shared", "jade-horizon.flight-key-ready"],
      relationshipChanges: { "jade-horizon.trust": 18 },
      timeCostMinutes: 12,
      consequence: "The truth costs time but makes the mountain route a shared risk.",
    },
    {
      id: "jade-horizon.choice.hide-fault",
      label: "Conceal the aircraft fault",
      requiredFlags: ["jade-horizon.aircraft-fault-known"],
      setFlags: ["jade-horizon.fault-hidden", "jade-horizon.flight-key-ready"],
      relationshipChanges: { "jade-horizon.trust": -20 },
      timeCostMinutes: 4,
      consequence: "The route opens quickly, but later action recovery becomes socially expensive.",
    },
    {
      id: "jade-horizon.choice.secure-train",
      label: "Trade the contract copy for passage",
      requiredFlags: ["jade-horizon.river-route-taken"],
      setFlags: ["jade-horizon.train-passage-secured"],
      relationshipChanges: { "jade-horizon.trust": 3 },
      timeCostMinutes: 20,
      consequence: "The train opens while the courier loses a piece of leverage.",
    },
  ],
  actions: [
    dynamixAction({
      id: "jade-horizon.action.train-roof",
      label: "Night-train roof crossing",
      kind: "vehicle",
      locationId: "jade-horizon.cliff-railway",
      durationTicks: 168,
      safeAnchorId: "jade-horizon.anchor.train-roof",
      windows: [
        {
          id: "jade-horizon.action.train-roof.duck",
          opensAtTick: 20,
          closesAtTick: 46,
          input: "down",
          telegraph: "A signal gantry enters the upper silhouette.",
          successBeat: "The protagonist drops into the carriage shadow.",
        },
        {
          id: "jade-horizon.action.train-roof.step",
          opensAtTick: 70,
          closesAtTick: 98,
          input: "right",
          telegraph: "A carriage gap opens beneath a held lightning frame.",
          successBeat: "One committed stride clears the coupling.",
        },
        {
          id: "jade-horizon.action.train-roof.grab",
          opensAtTick: 118,
          closesAtTick: 148,
          input: "act",
          telegraph: "A loose route case slides toward the roof edge.",
          successBeat: "The case is secured before the tunnel cut.",
        },
      ],
      timeCostMinutes: 18,
      successFlags: [
        "jade-horizon.train-roof-crossed",
        "jade-horizon.route-secured",
      ],
      failureFlags: ["jade-horizon.train-roof-failed"],
      successRelationshipChanges: {
        "jade-horizon.trust": 8,
        "jade-horizon.fatigue": 10,
      },
      failureRelationshipChanges: {
        "jade-horizon.trust": -4,
        "jade-horizon.fatigue": 14,
      },
      successConsequence: "The route case and both protagonists reach the railway intact.",
      failureConsequence:
        "The action returns to the roof-entry anchor without erasing route or trust history.",
    }),
  ],
  deadlines: [
    {
      id: "jade-horizon.deadline.railway",
      gameMinute: 60 * 24 + 60 * 12,
      requiredFlag: "jade-horizon.route-secured",
      failureOutcomeId: "jade-horizon.outcome.route-lost",
      warningMinutes: [240, 120, 60],
    },
  ],
  outcomes: [
    {
      id: "jade-horizon.outcome.shared-route",
      kind: "success",
      title: "THE ROUTE HOLDS",
      message: "The courier and pilot reach the railway with enough trust to finish the crossing.",
      requiredFlags: ["jade-horizon.route-secured"],
      minimumRelationships: { "jade-horizon.trust": 50 },
    },
    {
      id: "jade-horizon.outcome.broken-alliance",
      kind: "failure",
      title: "THE ALLIANCE BREAKS",
      message: "The route remains possible, but neither protagonist will continue beside the other.",
      requiredFlags: ["jade-horizon.route-secured"],
      minimumRelationships: { "jade-horizon.trust": 0 },
    },
    {
      id: "jade-horizon.outcome.route-lost",
      kind: "failure",
      title: "THE ROUTE CLOSES",
      message: "The deadline passes before the route case reaches the cliff railway.",
      requiredFlags: [],
      minimumRelationships: {},
    },
  ],
  designRules: [
    "Time costs must alter later routes or relationships rather than acting as decorative numbers.",
    "Protagonists keep separate knowledge, inventory and reasons for entering each scene.",
    "Travel montages preserve geography and causal state through three to five authored panels.",
    "Action failure restores a safe anchor without deleting investigation, route or relationship progress.",
  ],
};
