import type { AdventureProductionProfile } from "./production-profile-types.js";
import {
  actors,
  animation,
  audio,
  interfaceGrammar,
  palette,
  profile,
  scene,
  showcase,
} from "./production-profile-factory.js";
import { productionProfileSplashes as splashes } from "./production-profile-splashes.js";

export const verbProductionProfiles: readonly AdventureProductionProfile[] = [
  profile({
    id: "verb-panel-cartoon-vga",
    label: "Verb-Panel Cartoon VGA",
    family: "verb-panel-comedy",
    summary: "Bold cartoon rooms, persistent verbs, sentence construction and dense inventory play.",
    productionModes: ["graphic-cel", "painted-pixel"],
    compositionModes: ["comic-panel", "stage"],
    palette: palette(
      256,
      ["#0b1020", "#284968", "#3b866a", "#b35648", "#dda85d", "#f2e5bb"],
      "Use clean hue-shifted shadow ramps and readable outline contrast.",
      "Keep bright accents on faces, targets and comic reveals.",
      18,
    ),
    scene: scene(
      "Design rooms around readable object clusters and comic entrances.",
      "Reserve gameplay height above the verb and inventory panel.",
      "Actors, exits and manipulable objects lead through shape and colour.",
      "Moved, combined and misused objects leave persistent consequences.",
    ),
    actors: actors(
      "Graphic body shapes, expressive heads and readable held inventory.",
      [23, 39],
      "In-scene speech dominates; close-ups are rare comic events.",
      "Reaction poses make dialogue and object use visible.",
    ),
    animation: animation(
      "Pose-driven cartoon timing with readable anticipation and payoff.",
      [6, 10],
      "Short character business may run while the player considers verbs.",
      "Use explicit action clips and hard comic cuts.",
    ),
    interface: interfaceGrammar(
      "bottom-verb-panel",
      "verb-list",
      ["verb-list", "two-button"],
      32,
      true,
      "floating-subtitle",
      "A persistent grid of large icons below the sentence line.",
      "The sentence line previews verb, object and inventory intent.",
      "The pointer selects targets while verbs carry precise intent.",
      false,
    ),
    puzzleGrammars: ["inventory-chain", "comic-misapplication", "multi-route"],
    audio: audio(
      "Characterful location motifs with economical adaptive changes.",
      "Markets, docks, rooms and weather remain clear beneath dialogue.",
      "Brief comic signatures support discoveries and location cuts.",
      "Verb and inventory actions use quiet physical clicks.",
    ),
    splash: splashes.pulp,
    showcase: showcase(
      "showcase.saltwake-island",
      "Saltwake Island",
      "island comedy adventure",
      "A lighthouse apprentice must recover a tide chart before the island votes to move the sea.",
      [
        "A harbour square with clean object clusters above a verb panel.",
        "A tavern supporting several combinations and rewarding wrong uses.",
        "A lighthouse whose final machine state pays off earlier jokes.",
      ],
      ["verb panel", "sentence line", "inventory combinations", "comic feedback"],
    ),
    rule: "Provide clear goals without removing discovery.",
    prohibition: "Do not replace authored verbs with a generic radial menu.",
    reviewQuestions: [
      "Does the sentence line accurately preview every command?",
      "Can targets and actors be read above persistent chrome?",
      "Do wrong uses give concise characterful feedback?",
    ],
  }),
  profile({
    id: "pulp-archaeology-vga",
    label: "Pulp Archaeology VGA",
    family: "verb-panel-pulp",
    summary: "Grounded illustrated pulp, verb-led object logic, alternate routes and travel transitions.",
    productionModes: ["painted-pixel", "inked-comic"],
    compositionModes: ["cinematic", "travel", "stage"],
    palette: palette(
      256,
      ["#0c1015", "#293846", "#716049", "#9b774d", "#b45b43", "#d8caa8"],
      "Use grounded cool shadows and preserve material distinction.",
      "Reserve warm light for evidence, route decisions and danger.",
      16,
    ),
    scene: scene(
      "Frame museums, streets, vehicles and ruins as readable pulp locations.",
      "Protect practical approaches around desks, machinery and archaeology.",
      "The current question, route and evidence remain separate.",
      "Research, travel and route choices visibly alter access and personnel.",
    ),
    actors: actors(
      "Grounded adventure clothing, readable tools and distinct companion profiles.",
      [24, 41],
      "Selective close-ups support major confrontation or discovery.",
      "Confident movement, cautious inspection and differentiated companions.",
    ),
    animation: animation(
      "Measured exploration with clear object handling and action inserts.",
      [6, 10],
      "Observation and equipment gestures support professional identity.",
      "Travel and close-ups use hard editorial cuts and map motifs.",
    ),
    interface: interfaceGrammar(
      "bottom-verb-panel",
      "verb-list",
      ["verb-list", "two-button", "context"],
      30,
      true,
      "floating-subtitle",
      "Persistent inventory for play and a dossier for evidence.",
      "Sentence line plus restrained route and research feedback.",
      "A simple pointer works with verbs expressing precise intent.",
      false,
    ),
    puzzleGrammars: ["multi-route", "research-deduction", "inventory-chain", "hybrid-action"],
    audio: audio(
      "Pulp orchestral colours reduced to a disciplined digital palette.",
      "Museums, streets, engines, water and ruins carry geography.",
      "Travel, discovery and danger receive distinct motifs.",
      "Map, paper and inventory sounds remain physical and understated.",
    ),
    splash: splashes.pulp,
    showcase: showcase(
      "showcase.sunken-dial",
      "The Sunken Dial",
      "archaeological pulp mystery",
      "A conservator races an expedition to decode a machine charting tides beneath a lost city.",
      [
        "A museum office sharing one clear research and route objective.",
        "A dock workshop supporting diplomatic, technical and risky paths.",
        "A flooded chamber where machinery, water and evidence converge.",
      ],
      ["alternate routes", "verb panel", "research", "travel map"],
    ),
    rule: "Alternate routes must differ in play and consequence.",
    prohibition: "Do not use generic treasure imagery in place of researched material culture.",
    reviewQuestions: [
      "Does each route support a distinct player strategy?",
      "Are evidence and machinery readable above interface chrome?",
      "Do travel transitions preserve geography and urgency?",
    ],
  }),
] as const;
