import { actor, plate, prop, puzzle, showcase } from "./production-showcase-factory.js";

export const hollowValeShowcase = showcase({
  id: "the-hollow-vale",
  profileId: "gothic-rpg-vga",
  title: "The Hollow Vale",
  genre: "Gothic role-playing adventure",
  logline:
    "Three travellers with different disciplines enter a valley where night changes both roads and witnesses.",
  motif: "enchanted-belltower",
  titleTreatment:
    "A moonlit valley silhouette frames a distant watchtower, three small travellers and one unsafe road.",
  dialogueTreatment:
    "Painted portraits preserve equipment, injury, trust and class identity while the room remains visible.",
  systemTreatment:
    "A bound field journal presents attributes, resources, equipment, hour and learned actions without modern HUD chrome.",
  plates: [
    plate(
      "plate.hollow-vale.title",
      "title",
      "Moon over the closed vale",
      "Understand that time, danger and traveller discipline shape the journey.",
      224,
      72,
      118,
      "THE HOLLOW VALE",
      [],
      [
        prop(
          "prop.hollow-vale.watchtower",
          "ambience",
          232,
          46,
          42,
          88,
          "watchtower",
          "one-window-lit",
          false,
        ),
        prop(
          "prop.hollow-vale.road",
          "exit",
          134,
          132,
          78,
          28,
          "valley road",
          "moonlit",
          false,
        ),
      ],
      [
        "The title reads against five deliberate value groups at one-times native scale.",
        "The tower, road and travellers establish destination, route and party scale without copied imagery.",
        "Moonlight uses a controlled palette ramp rather than blur, bloom or soft alpha.",
      ],
    ),
    plate(
      "plate.hollow-vale.gameplay",
      "gameplay",
      "Ruined mill at the changing hour",
      "Cross the flooded mill race using a discipline-specific solution before the night patrol arrives.",
      222,
      106,
      102,
      "The wheel turns only when the valley wind falls.",
      [
        actor(
          "actor.hollow-vale.traveller",
          "player",
          84,
          164,
          54,
          "right",
          "prepared stance",
          "A dark cloak, pale hands and one class tool remain readable against wet stone.",
        ),
        actor(
          "actor.hollow-vale.watchman",
          "threat",
          266,
          146,
          48,
          "left",
          "distant patrol",
          "A narrow lantern and spear silhouette make the schedule threat legible before detail.",
        ),
      ],
      [
        prop(
          "prop.hollow-vale.mill-wheel",
          "puzzle",
          204,
          80,
          42,
          60,
          "mill wheel",
          "jammed",
        ),
        prop(
          "prop.hollow-vale.race-gate",
          "puzzle",
          156,
          126,
          30,
          30,
          "race gate",
          "flooded",
        ),
        prop(
          "prop.hollow-vale.high-path",
          "exit",
          286,
          92,
          28,
          62,
          "high path",
          "guarded",
        ),
      ],
      [
        "The lower walk lane stays continuous while the mill, flood and patrol remain separate focal groups.",
        "Fighter, magic and stealth tools can be staged at the same native interaction points.",
        "Patrol position, window light and water state visibly communicate the current hour.",
      ],
    ),
    plate(
      "plate.hollow-vale.dialogue",
      "dialogue",
      "The apothecary after midnight",
      "Learn why the patrol avoids the crypt without turning the witness into a generic hint dispenser.",
      184,
      96,
      108,
      "You carry the same frost as the people below.",
      [
        actor(
          "actor.hollow-vale.traveller-portrait",
          "player",
          86,
          174,
          78,
          "right",
          "guarded listening",
          "Equipment and injury remain part of the portrait identity rather than decorative overlays.",
        ),
        actor(
          "actor.hollow-vale.apothecary",
          "npc",
          230,
          164,
          72,
          "left",
          "measured warning",
          "The apothecary reads through posture, hands and lamp-side value separation.",
        ),
      ],
      [
        prop(
          "prop.hollow-vale.remedy",
          "clue",
          154,
          126,
          18,
          12,
          "frost remedy",
          "offered-conditionally",
        ),
        prop(
          "prop.hollow-vale.clock",
          "clue",
          282,
          48,
          22,
          28,
          "wall clock",
          "after-midnight",
          false,
        ),
      ],
      [
        "Portrait eyelines preserve the room and the conditional remedy between both speakers.",
        "Dialogue state reflects class, injury, prior help and the current hour.",
        "The clock and lamp carry schedule information without a persistent modern timer.",
      ],
    ),
    plate(
      "plate.hollow-vale.system",
      "system",
      "Traveller field journal",
      "Review resources, equipment, skills and the next dangerous hour before entering the crypt.",
      160,
      100,
      116,
      "NIGHT WATCH — THIRD HOUR",
      [
        actor(
          "actor.hollow-vale.journal-silhouette",
          "player",
          70,
          158,
          36,
          "right",
          "equipment study",
          "The small silhouette confirms current class gear beside the written character state.",
        ),
      ],
      [
        prop(
          "prop.hollow-vale.resource-runes",
          "puzzle",
          116,
          54,
          72,
          54,
          "resource ledger",
          "health-stamina-magic",
        ),
        prop(
          "prop.hollow-vale.class-tools",
          "clue",
          208,
          62,
          70,
          42,
          "class equipment",
          "current-loadout",
        ),
        prop(
          "prop.hollow-vale.time-wheel",
          "clue",
          212,
          128,
          50,
          28,
          "time wheel",
          "third-hour",
        ),
      ],
      [
        "Resources use distinct shape and labels rather than colour alone.",
        "Equipment, skill and time state remain inspectable before returning to the room.",
        "The journal reads as a period game surface rather than a modern dashboard.",
      ],
    ),
  ],
  puzzleBeats: [
    puzzle(
      "puzzle.hollow-vale.mill-crossing",
      "multi-route",
      "plate.hollow-vale.gameplay",
      "The mill race blocks the crypt road while a patrol approaches on a known schedule.",
      "Force the gate, redirect the water with learned magic, or climb through the machinery unseen.",
      "Each discipline reaches the road with different resource cost, witness state and later crypt access.",
      "Failure costs bounded health, stamina, magic or time, then returns the traveller to a safe approach state.",
    ),
    puzzle(
      "puzzle.hollow-vale.crypt-encounter",
      "hybrid-action",
      "plate.hollow-vale.system",
      "The crypt guardian interrupts exploration after the journal warns of the third-hour risk.",
      "Prepare equipment and resolve combat, warding or avoidance through the selected discipline.",
      "The guardian state, resource cost and next dialogue branch persist in the adventure world.",
      "Defeat restores the pre-encounter checkpoint and explains the missing preparation without losing prior puzzles.",
    ),
  ],
  originalityStatement:
    "Original travellers, valley, mill, apothecary, crypt, class routes, resource model, dialogue and visual language; no commercial character, room, interface artwork or puzzle is reproduced.",
});
