import { actor, plate, prop, puzzle, showcase } from "./production-showcase-factory.js";

export const afterHoursShowcase = showcase({
  id: "after-hours",
  profileId: "social-comedy-icon-vga",
  title: "After Hours",
  genre: "social comedy adventure",
  logline:
    "A stranded convention photographer has one night to recover a misplaced portfolio while every useful lead comes with an awkward social cost.",
  motif: "hotel-nightlife-corridor",
  titleTreatment:
    "A modest hotel key tag and flashbulb reflection assemble the title over a dark carpet-and-brass lobby composition.",
  dialogueTreatment:
    "Conversation stays mostly in scene with deliberate pauses, eyelines, awkward reaction holds and concise social feedback.",
  systemTreatment:
    "Score, money and inventory remain compact period surfaces; social consequence is communicated through people and access rather than relationship meters.",
  plates: [
    plate(
      "plate.after-hours.title",
      "title",
      "Hotel night title",
      "Establish grounded nightlife comedy without turning the setting into neon parody.",
      160,
      96,
      126,
      "AFTER HOURS",
      [],
      [
        prop("prop.after-hours.key-tag", "clue", 102, 74, 30, 18, "hotel key tag", "misplaced", false),
        prop("prop.after-hours.flash", "ambience", 210, 68, 18, 14, "camera flash", "spent", false),
      ],
      [
        "The title reads from simple brass, carpet and paper shapes at one-times scale.",
        "No nightclub neon wash or glossy modern title treatment.",
        "The visual joke is environmental rather than a meme reference.",
      ],
    ),
    plate(
      "plate.after-hours.lounge",
      "gameplay",
      "Hotel lounge",
      "Recover the first credible lead without losing access to the service corridor.",
      252,
      104,
      106,
      "The bartender remembers the portfolio. He also remembers the unpaid tab.",
      [
        actor(
          "actor.after-hours.photographer",
          "player",
          78,
          166,
          50,
          "right",
          "careful introduction",
          "Camera strap, jacket silhouette and one held hand remain readable before facial detail.",
        ),
        actor(
          "actor.after-hours.bartender",
          "npc",
          214,
          154,
          48,
          "left",
          "measured patience",
          "Apron, towel and squared posture carry the social read.",
        ),
      ],
      [
        prop("prop.after-hours.tab", "puzzle", 188, 108, 28, 18, "unpaid tab", "open"),
        prop("prop.after-hours.service-door", "exit", 278, 68, 34, 84, "service corridor door", "staff only"),
        prop("prop.after-hours-coat-check", "clue", 118, 126, 34, 28, "coat-check stand", "attended"),
      ],
      [
        "Tables frame social islands without blocking the walking lane.",
        "The bartender reaction changes visibly after payment or a credible alternative.",
        "Wrong social approaches remain reversible and produce specific feedback.",
      ],
    ),
    plate(
      "plate.after-hours.restaurant",
      "dialogue",
      "Late restaurant",
      "Use evidence and one borrowed coat to learn who carried the portfolio upstairs.",
      160,
      100,
      112,
      "That coat belongs to the keynote speaker. You are very much not the keynote speaker.",
      [
        actor(
          "actor.after-hours.photographer-close",
          "player",
          88,
          166,
          70,
          "right",
          "caught improvising",
          "Shoulders and camera strap retain identity under a larger reaction pose.",
        ),
        actor(
          "actor.after-hours-host",
          "npc",
          224,
          164,
          72,
          "left",
          "dry recognition",
          "Ledger, folded arms and one raised eyebrow read before facial detail.",
        ),
      ],
      [
        prop("prop.after-hours-coat", "puzzle", 142, 72, 38, 42, "borrowed coat", "wrong owner"),
        prop("prop.after-hours-receipt", "clue", 212, 112, 24, 14, "banquet receipt", "signed"),
      ],
      [
        "The conversation result changes available access rather than filling a relationship meter.",
        "Props provide mechanical alternatives to pure dialogue guessing.",
        "Comic timing is held in poses and response beats, not excessive animation.",
      ],
    ),
    plate(
      "plate.after-hours.penthouse",
      "system",
      "Penthouse corridor",
      "Resolve the final access problem using the social reputation and inventory state built through the night.",
      160,
      102,
      118,
      "ROOM 814 · DO NOT DISTURB",
      [
        actor(
          "actor.after-hours.photographer-system",
          "player",
          72,
          164,
          48,
          "right",
          "final approach",
          "The camera bag and coat state remain readable at native scale.",
        ),
      ],
      [
        prop("prop.after-hours-elevator", "exit", 40, 68, 36, 82, "elevator", "waiting"),
        prop("prop.after-hours-room814", "puzzle", 238, 66, 38, 84, "room 814", "latched"),
        prop("prop.after-hours-service-cart", "clue", 134, 122, 46, 34, "service cart", "unattended"),
      ],
      [
        "Earlier social choices alter who will answer or assist here.",
        "The final route has at least two valid solutions with different social consequences.",
        "Failure returns the player to a recoverable corridor state rather than a hidden dead end.",
      ],
    ),
  ],
  puzzleBeats: [
    puzzle(
      "puzzle.after-hours.lounge-access",
      "relationship-branch",
      "plate.after-hours.lounge",
      "The bartender controls a useful service route but remembers an unpaid tab.",
      "Resolve the tab honestly, trade a useful favour, or find another clue before trying the staff route again.",
      "The bartender's posture and the service-door state change when the relationship problem is resolved.",
      "Bad introductions cost time or dignity but do not permanently poison the route.",
    ),
    puzzle(
      "puzzle.after-hours.coat-confusion",
      "comic-misapplication",
      "plate.after-hours.restaurant",
      "A borrowed coat creates access and identification opportunities but also exposes the player if used carelessly.",
      "Combine the coat with receipt/context clues rather than treating disguise as a universal bypass.",
      "The host reveals the penthouse lead and the coat remains a situational tool rather than a magic key.",
      "Incorrect claims produce a short specific reaction and preserve an alternate path.",
    ),
  ],
  originalityStatement:
    "Original hotel, characters, social situations, props and dialogue; no proprietary Leisure Suit Larry room, character, joke or puzzle is reproduced.",
});
