import { actor, plate, prop, puzzle, showcase } from "./production-showcase-factory.js";

export const openCaseShowcase = showcase({
  id: "open-case",
  profileId: "procedural-investigation-vga",
  title: "Open Case",
  genre: "Procedural crime investigation",
  logline:
    "A city investigator must preserve a fragile evidence chain while a witness changes their account.",
  motif: "rain-bookshop",
  titleTreatment:
    "A rain-dark evidence office, one incomplete caseboard and a sealed apartment door frame the title.",
  dialogueTreatment:
    "Witness portraits remain grounded and evidence-led, with visible notes and credibility changes beside the room.",
  systemTreatment:
    "A paper caseboard links custody, analysis, testimony and locations without becoming a generic objective list.",
  plates: [
    plate(
      "plate.open-case.title",
      "title",
      "Caseboard before dawn",
      "Understand that observation, custody and testimony must survive scrutiny.",
      218,
      92,
      112,
      "OPEN CASE",
      [],
      [
        prop(
          "prop.open-case.caseboard",
          "clue",
          186,
          46,
          92,
          72,
          "caseboard",
          "one-thread-missing",
          false,
        ),
        prop(
          "prop.open-case.sealed-door",
          "exit",
          20,
          54,
          54,
          102,
          "sealed apartment door",
          "awaiting-entry",
          false,
        ),
      ],
      [
        "The title, sealed door and incomplete board remain readable in five restrained value groups.",
        "Rain and fluorescent light use hard native clusters rather than blur or bloom.",
        "The scene promises procedural consequence without copied police branding or commercial imagery.",
      ],
    ),
    plate(
      "plate.open-case.gameplay",
      "gameplay",
      "Apartment evidence boundary",
      "Document and collect the fragile scene without contaminating the route to the witness.",
      202,
      112,
      102,
      "The room records every shortcut.",
      [
        actor(
          "actor.open-case.investigator",
          "player",
          82,
          166,
          54,
          "right",
          "gloved observation",
          "Coat, gloves, notebook and camera remain distinct against the apartment floor.",
        ),
        actor(
          "actor.open-case.scene-officer",
          "npc",
          274,
          154,
          50,
          "left",
          "boundary watch",
          "A stable uniform silhouette marks the controlled entry without dominating evidence.",
        ),
      ],
      [
        prop(
          "prop.open-case.entry-log",
          "puzzle",
          22,
          126,
          34,
          22,
          "entry log",
          "unsigned",
        ),
        prop(
          "prop.open-case.glass-fragment",
          "clue",
          174,
          142,
          18,
          8,
          "glass fragment",
          "unphotographed",
        ),
        prop(
          "prop.open-case.evidence-bag",
          "puzzle",
          228,
          132,
          24,
          18,
          "evidence bag",
          "unused",
        ),
        prop(
          "prop.open-case.witness-route",
          "exit",
          286,
          82,
          28,
          72,
          "witness route",
          "held-until-release",
        ),
      ],
      [
        "The protected entry, evidence zone, equipment and witness exit remain separate interaction groups.",
        "Observation, photography, collection and custody state can be shown through physical prop changes.",
        "The investigator walk lane remains clear without allowing the actor to cross the protected evidence.",
      ],
    ),
    plate(
      "plate.open-case.dialogue",
      "dialogue",
      "Witness account under review",
      "Test the changing account against lawful evidence without revealing information the case has not earned.",
      178,
      98,
      106,
      "I never said the window was open.",
      [
        actor(
          "actor.open-case.investigator-portrait",
          "player",
          92,
          174,
          78,
          "right",
          "measured question",
          "Notebook, neutral posture and eye line keep the interviewer grounded and readable.",
        ),
        actor(
          "actor.open-case.witness",
          "npc",
          228,
          166,
          74,
          "left",
          "account revised",
          "The witness changes through hands, gaze and posture rather than exaggerated emotion.",
        ),
      ],
      [
        prop(
          "prop.open-case.interview-notes",
          "clue",
          144,
          132,
          32,
          22,
          "interview notes",
          "contradiction-marked",
        ),
        prop(
          "prop.open-case.photo-reference",
          "clue",
          270,
          92,
          30,
          24,
          "scene photograph",
          "available-if-documented",
        ),
      ],
      [
        "Questions appear only when supported by collected evidence and prior testimony.",
        "Portrait eyelines preserve the notes and photograph as the cause of the contradiction.",
        "Credibility changes are visible through performance and case state rather than a gamified meter.",
      ],
    ),
    plate(
      "plate.open-case.system",
      "system",
      "Custody and caseboard review",
      "Verify that each conclusion can be traced through collection, custody, analysis and testimony.",
      160,
      96,
      112,
      "CHAIN COMPLETE — LAB ROUTE OPEN",
      [
        actor(
          "actor.open-case.board-marker",
          "player",
          58,
          164,
          32,
          "right",
          "case location marker",
          "A small investigator marker distinguishes current location from evidence and witness cards.",
        ),
      ],
      [
        prop(
          "prop.open-case.custody-card",
          "puzzle",
          92,
          52,
          66,
          48,
          "custody card",
          "signed-and-sealed",
        ),
        prop(
          "prop.open-case.analysis-card",
          "clue",
          190,
          52,
          64,
          48,
          "analysis card",
          "lab-route-open",
        ),
        prop(
          "prop.open-case.witness-thread",
          "clue",
          132,
          122,
          80,
          30,
          "witness thread",
          "contradiction-linked",
        ),
      ],
      [
        "Every board connection names a retained evidence or testimony state.",
        "Custody, analysis and witness cards differ through shape and labels rather than colour alone.",
        "The board reads as an authored case file rather than a modern quest or objective tracker.",
      ],
    ),
  ],
  puzzleBeats: [
    puzzle(
      "puzzle.open-case.fragile-chain",
      "research-deduction",
      "plate.open-case.gameplay",
      "A glass fragment can identify the route only if the scene and custody sequence remain defensible.",
      "Log entry, photograph context, collect with the correct equipment and seal the custody record.",
      "The lab route opens and the resulting analysis can lawfully support the witness contradiction.",
      "An invalid handling attempt explains the break, resets only the uncommitted collection step and preserves observations.",
    ),
    puzzle(
      "puzzle.open-case.witness-account",
      "topic-investigation",
      "plate.open-case.dialogue",
      "The witness account conflicts with the documented window state but only after the evidence chain is complete.",
      "Establish the original account, introduce the supported photograph and ask the unlocked contradiction topic.",
      "The testimony changes, the caseboard links the witness to the route and a new location becomes available.",
      "A premature accusation closes the unsupported topic temporarily; lawful evidence reopens it without losing case state.",
    ),
  ],
  originalityStatement:
    "Original investigator, witness, apartment, evidence chain, caseboard, dialogue, locations and procedural puzzles; no commercial character, badge, interface artwork, crime scene or script is reproduced.",
});
