import { actor, plate, prop, puzzle, showcase } from "./production-showcase-factory.js";

export const nightShiftShowcase = showcase({
  id: "night-shift",
  profileId: "early-procedural-icon-vga",
  title: "Night Shift",
  genre: "Early procedural VGA adventure",
  logline:
    "A municipal night-duty officer leaves a routine briefing for patrol, then has to read one ordinary roadside stop carefully enough to prevent a small situation becoming a bad one.",
  motif: "municipal-night-shift",
  titleTreatment:
    "A wet municipal street, fluorescent station windows and one parked patrol sedan hold the title in restrained painted VGA values with no modern police branding.",
  dialogueTreatment:
    "Conversation remains in the room with small grounded figures, readable eyelines and short native text; occasional closer framing is an authored cut, not a permanent portrait UI.",
  systemTreatment:
    "A compact duty/equipment surface and restrained score/failure text prove procedure without a caseboard, objective tracker or simulation HUD.",
  plates: [
    plate(
      "plate.night-shift.title",
      "title",
      "Rain outside the municipal station",
      "Read the place, hour and grounded contemporary tone before the first icon interaction.",
      184,
      94,
      108,
      "NIGHT SHIFT",
      [],
      [
        prop(
          "prop.night-shift.station-windows",
          "ambience",
          34,
          44,
          108,
          72,
          "station windows",
          "fluorescent-night",
          false,
        ),
        prop(
          "prop.night-shift.patrol-car",
          "ambience",
          198,
          123,
          92,
          42,
          "municipal patrol sedan",
          "parked-wet",
          false,
        ),
      ],
      [
        "The station, pavement and sedan resolve as broad hand-painted value groups before small detail is added.",
        "Wet surfaces use controlled pixel clusters and selective ordered dithering rather than blur, bloom or reflective shaders.",
        "The frame reads as an original early-1990s VGA municipal night scene rather than modern pixel art or copied police imagery.",
      ],
    ),
    plate(
      "plate.night-shift.gameplay",
      "gameplay",
      "Briefing room equipment check",
      "Collect the ordinary duty equipment, understand the shift instruction and leave through the correct station exit.",
      210,
      118,
      104,
      "You are not ready to take the car yet.",
      [
        actor(
          "actor.night-shift.officer",
          "player",
          68,
          169,
          48,
          "right",
          "listening at ease",
          "A small proportionate uniformed figure with readable belt, hands and cap silhouette; no oversized head or heavy outline.",
        ),
        actor(
          "actor.night-shift.desk-sergeant",
          "npc",
          226,
          145,
          46,
          "left",
          "paperwork pause",
          "A seated working silhouette stays distinct from the desk without using portrait-scale exaggeration.",
        ),
      ],
      [
        prop(
          "prop.night-shift.radio",
          "puzzle",
          112,
          123,
          16,
          12,
          "portable radio",
          "on-charging-rack",
        ),
        prop(
          "prop.night-shift.keys",
          "puzzle",
          151,
          128,
          12,
          6,
          "vehicle keys",
          "on-hook",
        ),
        prop(
          "prop.night-shift.briefing-sheet",
          "clue",
          218,
          118,
          20,
          14,
          "briefing sheet",
          "unread",
        ),
        prop(
          "prop.night-shift.station-exit",
          "exit",
          282,
          68,
          30,
          98,
          "station exit",
          "held-until-ready",
        ),
      ],
      [
        "The radio, keys and briefing sheet remain clickable at one-times native size without being enlarged into game icons inside the room.",
        "The officer can pass behind the desk corner and door frame through authored baseline occlusion while retaining a clear foot lane.",
        "Approach slots place the officer correctly at the charging rack, key hook, desk and exit instead of stopping at arbitrary shortest-path points.",
        "Procedure failure is explained through short narration and room state rather than a checklist panel.",
      ],
    ),
    plate(
      "plate.night-shift.dialogue",
      "dialogue",
      "Late diner witness conversation",
      "Separate one useful observation from ordinary late-night conversation without turning the diner into an evidence-board scene.",
      205,
      108,
      110,
      "The blue delivery van? It was here before the rain got heavy.",
      [
        actor(
          "actor.night-shift.officer-diner",
          "player",
          92,
          170,
          50,
          "right",
          "notebook lowered",
          "The officer remains a small in-scene figure with readable face direction and notebook hand.",
        ),
        actor(
          "actor.night-shift.server",
          "npc",
          218,
          162,
          48,
          "left",
          "remembering the parking lot",
          "Eyeline, hand position and counter spacing carry the performance without a permanent portrait box.",
        ),
      ],
      [
        prop(
          "prop.night-shift.coffee-pot",
          "ambience",
          244,
          112,
          16,
          24,
          "coffee pot",
          "half-full",
        ),
        prop(
          "prop.night-shift.receipt-spike",
          "clue",
          179,
          127,
          12,
          10,
          "receipt spike",
          "one-blue-van-ticket",
        ),
        prop(
          "prop.night-shift.front-window",
          "ambience",
          26,
          46,
          82,
          74,
          "rainy front window",
          "traffic-passing",
          false,
        ),
      ],
      [
        "The counter, server, officer, receipt spike and rain window remain separate focal groups in a believable small diner.",
        "Dialogue text preserves the room and uses native bitmap typography rather than modern speech cards.",
        "The useful observation is supported by one physical receipt clue but does not open a caseboard or gamified credibility meter.",
      ],
    ),
    plate(
      "plate.night-shift.system",
      "system",
      "Patrol readiness and failure recovery",
      "Verify duty equipment, current score and a bounded restart/restore path before returning to the street.",
      158,
      94,
      108,
      "READY FOR PATROL · 12 / 12",
      [
        actor(
          "actor.night-shift.system-marker",
          "player",
          54,
          165,
          34,
          "right",
          "small duty marker",
          "The current officer marker stays subordinate to the equipment and score information.",
        ),
      ],
      [
        prop(
          "prop.night-shift.radio-status",
          "puzzle",
          82,
          58,
          42,
          32,
          "radio status",
          "checked",
        ),
        prop(
          "prop.night-shift.keys-status",
          "puzzle",
          139,
          58,
          42,
          32,
          "vehicle keys status",
          "collected",
        ),
        prop(
          "prop.night-shift.briefing-status",
          "clue",
          196,
          58,
          56,
          32,
          "briefing note",
          "read",
        ),
        prop(
          "prop.night-shift.restart-control",
          "exit",
          228,
          132,
          62,
          24,
          "restore or restart",
          "available-after-failure",
        ),
      ],
      [
        "The duty surface reads like a compact period modal panel rather than a modern loadout grid.",
        "Visible score is restrained and tied to authored consequential actions, not constant achievement popups.",
        "Failure recovery clearly offers restore/restart without leaving hidden transient movement, entry or interaction state behind.",
      ],
    ),
  ],
  puzzleBeats: [
    puzzle(
      "puzzle.night-shift.readiness",
      "inventory-chain",
      "plate.night-shift.gameplay",
      "The station exit should not release the officer until the radio, keys and shift instruction are physically accounted for.",
      "Read the briefing sheet, collect the charged radio, then take the vehicle keys before using the station exit.",
      "The exit becomes available, the score advances and the patrol transition can begin through its authored entry/exit choreography.",
      "Leaving early returns short procedural narration and preserves all equipment already collected; nothing is silently consumed.",
    ),
    puzzle(
      "puzzle.night-shift.roadside-order",
      "environmental-state",
      "plate.night-shift.gameplay",
      "A routine roadside interaction becomes unsafe if the officer approaches or acts before reading the vehicle and driver state.",
      "Observe the stopped vehicle, use the authored approach lane, speak before reaching into the vehicle area and react to the changed driver pose.",
      "The stop resolves safely and unlocks the later diner observation without creating a modern mission objective.",
      "An unsafe action triggers explicit failure and a bounded restore/restart path while preserving reproducible save state.",
    ),
  ],
  originalityStatement:
    "Original municipal station, officer, desk sergeant, roadside stop, diner, server, patrol equipment, dialogue and procedural puzzles; no commercial badge, character, room layout, police department branding, script or artwork is reproduced.",
});
