import type { AdventureProductionProfile } from "./production-profile-types.js";
import {
  actors,
  animation,
  audio,
  interfaceGrammar,
  palette,
  profile,
  scene,
  showcase,
} from "./production-profile-factory.js";
import { productionProfileSplashes as splashes } from "./production-profile-splashes.js";

export const iconProductionProfiles: readonly AdventureProductionProfile[] = [
  profile({
    id: "storybook-icon-vga",
    label: "Storybook Icon VGA",
    family: "icon-storybook",
    summary: "Painterly fairytale rooms, compact icon interaction and visible environmental consequence.",
    productionModes: ["storybook-gouache", "painted-pixel"],
    compositionModes: ["storybook", "stage"],
    palette: palette(
      256,
      ["#10131a", "#35435c", "#6f8d69", "#c19a62", "#e6d5a8", "#f3f0df"],
      "Use one coherent cool shadow family and reserve black for depth cuts.",
      "Use narrow warm ramps to lead the eye toward story objectives.",
    ),
    scene: scene(
      "Compose each room as a stable illustrated tableau.",
      "Protect a broad lower-middle actor lane and clear arrival islands.",
      "One narrative focus leads; exits and secondary clues remain legible.",
      "Make solved puzzles and chapter changes visible in room art.",
    ),
    actors: actors(
      "Readable storybook proportions with clear head, hands and carried items.",
      [24, 42],
      "Painted close portraits with restrained expression changes.",
      "Held poses and readable reactions outrank smooth generic motion.",
    ),
    animation: animation(
      "Economical held-frame performance with deliberate key poses.",
      [6, 10],
      "Use rare characterful idles that never compete with objectives.",
      "Give turns, starts and stops explicit readable poses.",
    ),
    interface: interfaceGrammar(
      "top-icon-bar",
      "icon-bar",
      ["icon-bar", "context"],
      0,
      false,
      "portrait-box",
      "A framed modal inventory with large object silhouettes.",
      "Brief illustrated narration and compact score feedback.",
      "Walk, look, hand, talk and inventory cursors remain distinct.",
      true,
    ),
    puzzleGrammars: ["environmental-state", "inventory-chain", "multi-route"],
    audio: audio(
      "Melodic room themes with small instrumental palettes.",
      "Birds, water, wind and interiors define place beneath music.",
      "Short motifs mark discovery, danger and chapter movement.",
      "Soft tactile clicks and page sounds match the illustrated world.",
    ),
    splash: splashes.lantern,
    showcase: showcase(
      "showcase.glass-finch",
      "The Glass Finch",
      "storybook fantasy mystery",
      "A bell keeper follows a glass bird through a valley whose songs are being stolen.",
      [
        "A painted village square with one blocked belfry route and readable icon targets.",
        "A river crossing whose water and witness change after each solution.",
        "A witch-light orchard resolving the mystery through environmental state and song.",
      ],
      ["icon bar", "score", "environmental puzzles", "painted portraits"],
    ),
    rule: "Let illustration and musical identity carry wonder.",
    prohibition: "Do not replace authored danger with arbitrary punishment.",
    reviewQuestions: [
      "Does the room read as an illustration before the cursor moves?",
      "Can the actor and carried item be read at 1× scale?",
      "Does every solved puzzle visibly alter the world?",
    ],
  }),
  profile({
    id: "comic-scifi-icon-vga",
    label: "Comic Science-Fiction Icon VGA",
    family: "icon-comic",
    summary: "Bright graphic science fiction, comic silhouettes, icon interaction and joke-rich props.",
    productionModes: ["graphic-cel", "painted-pixel"],
    compositionModes: ["comic-panel", "stage"],
    palette: palette(
      256,
      ["#080b17", "#28345f", "#3f8f8f", "#bd604b", "#e5bd68", "#f4f0da"],
      "Use saturated dark ramps rather than neutral mud.",
      "Reserve hard bright accents for technology, faces and joke reveals.",
      14,
    ),
    scene: scene(
      "Stage rooms as graphic comic sets with bold prop silhouettes.",
      "Keep a generous walk strip beneath machinery and signage.",
      "The immediate task and visual joke must not compete.",
      "Broken, repaired and misused technology must visibly change.",
    ),
    actors: actors(
      "Exaggerated body shapes, readable tools and strong reaction poses.",
      [23, 40],
      "Occasional comic close-ups use hard shadow and broad expression.",
      "Anticipation, impact and reaction poses carry humour.",
    ),
    animation: animation(
      "Snappy pose-to-pose animation with strategic held punch lines.",
      [6, 8],
      "Short visual-business loops reveal personality or malfunction.",
      "Use explicit turns and recoil rather than interpolated easing.",
    ),
    interface: interfaceGrammar(
      "top-icon-bar",
      "icon-bar",
      ["icon-bar", "context"],
      0,
      false,
      "floating-subtitle",
      "Compact illustrated inventory with comic object descriptions.",
      "Dry narration and immediate visual feedback.",
      "Action icons remain legible against saturated technology palettes.",
      true,
    ),
    puzzleGrammars: ["comic-misapplication", "inventory-chain", "environmental-state"],
    audio: audio(
      "Compact FM-style motifs with mechanical counterpoints.",
      "Machinery, ventilation and announcements support the jokes.",
      "Brief electronic punctuation marks success and failure.",
      "Dry switches and chirps avoid modern glossy feedback.",
    ),
    splash: splashes.comic,
    showcase: showcase(
      "showcase.vacuum-courtesy",
      "Vacuum Courtesy",
      "science-fiction workplace comedy",
      "A sanitation courier must repair an orbital station before its bureaucracy notices it is missing.",
      [
        "A docking office with one readable route and comic machine states.",
        "A sanitation tunnel rewarding both correct and entertaining tool use.",
        "A control chamber whose repaired systems produce a staged punch line.",
      ],
      ["icon bar", "comic feedback", "machine states", "FM-style splash"],
    ),
    rule: "Every visual joke must preserve puzzle readability.",
    prohibition: "Do not substitute meme references for authored comedy.",
    reviewQuestions: [
      "Are actors and machines readable before internal detail?",
      "Does failed object use reward curiosity without obscuring the route?",
      "Are animation holds timed as punch lines rather than loading gaps?",
    ],
  }),
  profile({
    id: "gothic-investigation-vga",
    label: "Gothic Investigation VGA",
    family: "portrait-investigation",
    summary: "Moody painted rooms, portrait-led conversation, research topics and chapter investigation.",
    productionModes: ["painted-pixel", "inked-comic"],
    compositionModes: ["cinematic", "stage"],
    palette: palette(
      256,
      ["#090a10", "#252838", "#53434b", "#75634f", "#a68c68", "#d2c5aa"],
      "Preserve readable faces and clue planes inside deep cool interiors.",
      "Use warm practical light to isolate evidence and social tension.",
      16,
    ),
    scene: scene(
      "Use grounded cinematic rooms with strong doorway and portrait eyelines.",
      "Move deliberately between research, witness and exit islands.",
      "Evidence and character tension outrank decorative gothic detail.",
      "Time, weather, witness availability and evidence alter each room.",
    ),
    actors: actors(
      "Grounded coats and posture with readable hands, notebooks and evidence.",
      [25, 43],
      "Large painted portraits use controlled expression and directional light.",
      "Eyeline, pause and guarded posture matter more than broad movement.",
    ),
    animation: animation(
      "Measured movement, long atmospheric holds and selective facial change.",
      [6, 10],
      "Rare gestures support suspicion, fatigue or private thought.",
      "Use short cuts, room fades and portrait changes with authored rhythm.",
    ),
    interface: interfaceGrammar(
      "portrait-topic-panel",
      "icon-bar",
      ["icon-bar", "context"],
      0,
      false,
      "topic-ledger",
      "Evidence objects and notebook pages share a framed view.",
      "Narration, recorder and chapter cues stay separate from topics.",
      "Action cursors and topic selection make intent explicit.",
      true,
    ),
    puzzleGrammars: ["topic-investigation", "research-deduction", "environmental-state"],
    audio: audio(
      "Dark chamber motifs and location themes evolve with evidence.",
      "Rain, rooms, bells and streets sustain investigative tension.",
      "Thematic cells mark revelation, danger and chapter closure.",
      "Paper, recorder and evidence sounds remain tactile and dry.",
    ),
    splash: splashes.celestial,
    showcase: showcase(
      "showcase.red-ledger",
      "The Red Ledger",
      "urban folklore investigation",
      "A municipal archivist follows an impossible debt through a rain-bound harbour city.",
      [
        "A lamplit archive where disturbed records establish a research question.",
        "A service alley where witness topics and evidence open the route.",
        "A river chapel whose symbols, portraits and sound resolve the deduction.",
      ],
      ["topic dialogue", "evidence notebook", "chapter changes", "painted portraits"],
    ),
    rule: "Information delivery must change understanding, not only flags.",
    prohibition: "Do not use arbitrary occult imagery without cultural and narrative cause.",
    reviewQuestions: [
      "Does each chapter state change the room and testimony?",
      "Are clue, topic and research relationships clear without a tracker?",
      "Do portraits preserve identity under the lighting doctrine?",
    ],
  }),
] as const;
