import {
  actors,
  animation,
  audio,
  interfaceGrammar,
  palette,
  profile,
  scene,
  showcase,
} from "./production-profile-factory.js";
import { productionProfileSplashes as splashes } from "./production-profile-splashes.js";
import type { AdventureProductionProfile } from "./production-profile-types.js";

export const specialistProductionProfiles: readonly AdventureProductionProfile[] = [
  profile({
    id: "gothic-rpg-vga",
    label: "Gothic Role-Playing VGA",
    family: "gothic-rpg",
    summary:
      "Moonlit exploration, class-specific problem solving, scheduled characters, resources and bounded combat.",
    productionModes: ["painted-pixel", "inked-comic"],
    compositionModes: ["stage", "cinematic", "travel"],
    palette: palette(
      256,
      ["#070912", "#20243d", "#47435f", "#6a4f57", "#a78872", "#d8c9ae"],
      "Keep the lowest values cool and reserve true black for depth cuts, silhouettes and danger.",
      "Use moonlight, fire and spell accents as narrow readable ramps rather than broad modern glow.",
      16,
    ),
    scene: scene(
      "Compose villages, wild routes and interiors as readable Gothic stages with visible time and weather state.",
      "Protect travel lanes, encounter pockets and safe interaction islands across the lower half.",
      "The current danger, available route and class opportunity must remain visually distinct.",
      "Day, night, weather, solved obstacles and character schedules visibly alter every revisited location.",
    ),
    actors: actors(
      "Readable class equipment, hands and carried tools with grounded proportions and strong night silhouettes.",
      [24, 43],
      "Painted conversation portraits preserve identity while showing fatigue, injury, trust and threat.",
      "Movement, guarded stance, spell preparation and combat recovery use explicit authored poses.",
    ),
    animation: animation(
      "Measured exploration with economical walk cycles and readable action, defence, hit and recovery beats.",
      [6, 10],
      "Scheduled work, watch and rest loops communicate place without becoming ambient noise.",
      "Turns, combat entry, spell preparation and defeat recovery use deterministic native-tick holds.",
    ),
    interface: interfaceGrammar(
      "top-icon-bar",
      "icon-bar",
      ["icon-bar", "context"],
      0,
      false,
      "portrait-box",
      "A modal equipment and inventory book shares visual language with the character sheet.",
      "Health, stamina, magic, time and class information appear in authored modal surfaces, not a modern HUD.",
      "Walk, look, use, talk, inventory, character and magic intents remain explicit.",
      false,
    ),
    puzzleGrammars: ["multi-route", "hybrid-action", "environmental-state", "relationship-branch"],
    audio: audio(
      "Dark chamber colours, folk instruments and restrained thematic development follow location and time.",
      "Wind, snow, forest, interiors and distant creatures establish danger beneath sparse music.",
      "Short motifs mark class success, discovery, combat danger and the changing hour.",
      "Inventory, spell, weapon and character-sheet sounds remain dry, physical and period-scaled.",
    ),
    splash: splashes.celestial,
    showcase: showcase(
      "showcase.hollow-vale",
      "The Hollow Vale",
      "Gothic role-playing adventure",
      "Three travellers with different disciplines enter a valley where night changes both roads and witnesses.",
      [
        "A moonlit village crossroads whose exits, watch patrol and hazards change with the hour.",
        "A ruined mill obstacle supporting martial, magical and stealth solutions with distinct later consequences.",
        "A crypt approach where resources, equipment, combat recovery and prior relationships converge.",
      ],
      ["classes", "skills", "resources", "day and night", "schedules", "combat", "character transfer"],
    ),
    rule: "Every class route must differ in actions, costs, feedback and later consequence.",
    prohibition: "Do not disguise one generic solution behind three differently labelled buttons.",
    reviewQuestions: [
      "Can class equipment and resource state be understood without persistent modern chrome?",
      "Does time visibly change routes, danger and character availability?",
      "Can every combat or skill failure recover without corrupting adventure state?",
    ],
  }),
  profile({
    id: "early-procedural-icon-vga",
    label: "Early Procedural Icon VGA",
    family: "procedural-icon",
    summary:
      "Early-1990s Sierra-style procedural adventure with grounded contemporary places, compact icon interaction, score feedback and direct readable consequences.",
    productionModes: ["painted-pixel"],
    compositionModes: ["stage", "cinematic"],
    palette: palette(
      256,
      ["#0b1117", "#27343d", "#52616a", "#7c6658", "#b39b7b", "#ded6c2"],
      "Build shadows from a few material-specific cool or neutral ramps. Do not outline every object or crush all interiors to black.",
      "Use practical daylight, fluorescents, street lamps and vehicle lights as restrained painted value shifts, never modern bloom.",
      18,
    ),
    scene: scene(
      "Compose stations, offices, diners, streets and roadside scenes from believable eye-level observation with broad hand-painted masses and simple early-VGA perspective.",
      "Protect a generous lower-half walking lane, then author specific approach positions around desks, doors, vehicles and small equipment.",
      "Readable duty action, person and exit take priority over decorative density; mundane architecture should remain convincing rather than stylised into generic pixel art.",
      "Doors, equipment, vehicles and procedural state visibly change the working room without adding modern mission UI.",
    ),
    actors: actors(
      "Use small proportionate contemporary figures with clean uniforms, coats and readable hand poses; avoid oversized chibi heads or universal dark outlines.",
      [22, 38],
      "Conversation remains primarily in-scene; close portraits are occasional authored inserts rather than the default dialogue surface.",
      "Walking, turning, reaching, writing, radio use and vehicle interaction use economical held poses with clear foot grounding.",
    ),
    animation: animation(
      "Deliberate early-VGA movement with visible turn/start/stop beats, six-to-eight-frame walks and discrete object-use poses.",
      [6, 8],
      "Ambient staff activity is sparse and functional: typing, filing, waiting, traffic or a short radio gesture.",
      "Interaction choreography uses anticipation, action and recovery holds instead of procedural IK or smooth modern blending.",
    ),
    interface: interfaceGrammar(
      "top-icon-bar",
      "icon-bar",
      ["icon-bar", "context"],
      0,
      false,
      "floating-subtitle",
      "Inventory and duty equipment live in a compact modal surface with native bitmap labels and no card-grid styling.",
      "Short narration/procedure text and restrained score feedback appear without a persistent objective tracker or caseboard.",
      "Walk, look, use, talk, inventory and system intents stay explicit; tiny props may use invisible native click comfort but never glow or pulse.",
      true,
    ),
    puzzleGrammars: ["environmental-state", "inventory-chain", "research-deduction"],
    audio: audio(
      "Sparse location cues with dry early-digital/MIDI colour leave long stretches for room tone and procedural feedback.",
      "Traffic, rain, fluorescent hum, radios, paper, doors and footsteps carry most of the contemporary atmosphere.",
      "Short restrained stings mark correct duty steps, danger and scene transitions without cinematic scoring inflation.",
      "Icon, inventory and practical equipment sounds are short, dry and tactile.",
    ),
    splash: splashes.noir,
    showcase: showcase(
      "showcase.night-shift",
      "Night Shift",
      "Early procedural VGA adventure",
      "A night-duty municipal officer moves from briefing to patrol while one routine stop becomes a small, stateful investigation.",
      [
        "A fluorescent briefing room with believable desks, a locker/equipment corner, a doorway foreground plane and small native interaction targets.",
        "A wet roadside stop using authored walk lanes, vehicle foreground occlusion, practical night value groups and procedure-driven actor approaches.",
        "A late diner/interview scene where ordinary architecture, dialogue staging and one physical clue remain readable without a modern case UI.",
      ],
      [
        "SCI1-style icon interaction",
        "footprint-aware walk staging",
        "approach slots",
        "stateful doors and traversal",
        "baseline foreground occlusion",
        "entry choreography",
        "procedural feedback",
        "score/failure recovery",
      ],
    ),
    rule:
      "Every procedural action must read as a physical action in a believable room before it reads as a game rule.",
    prohibition:
      "Do not turn early procedural VGA into later case-management UI, photoreal concept art, generic chunky pixel art or a modern police-simulator HUD.",
    reviewQuestions: [
      "Could the native frame plausibly belong to a professional 1991–1993 VGA adventure rather than a current indie pixel-art game?",
      "Do doors, desks, vehicles, people and small equipment remain readable at one-times 320 by 200 without glowing assistance?",
      "Does the player understand why a procedural action worked or failed from room state, narration and animation rather than an objective checklist?",
    ],
  }),
  profile({
    id: "procedural-investigation-vga",
    label: "Procedural Investigation VGA",
    family: "procedural-investigation",
    summary:
      "Grounded crime-scene work, evidence custody, procedural order, interrogation and inspectable case state.",
    productionModes: ["painted-pixel", "inked-comic"],
    compositionModes: ["stage", "cinematic"],
    palette: palette(
      256,
      ["#090c11", "#26313a", "#4d5a5f", "#765a50", "#b08b67", "#ddd2bd"],
      "Use cool institutional shadows and keep evidence readable without theatrical colour coding.",
      "Reserve warm practical light and one restrained evidence accent for consequential detail.",
      18,
    ),
    scene: scene(
      "Stage precincts, streets and crime scenes as grounded working environments with explicit access boundaries.",
      "Preserve clean approach lanes around evidence, witnesses, exits and required equipment.",
      "Procedure, evidence and human testimony must occupy separate readable focal groups.",
      "Collection, custody, analysis and interview progress visibly alter the scene and caseboard.",
    ),
    actors: actors(
      "Grounded uniforms, coats, equipment and posture with clear hands and evidence-handling poses.",
      [25, 43],
      "Controlled portraits favour eyeline, fatigue and credibility over melodramatic expression.",
      "Observation, collection, note-taking and interview reactions use deliberate economical performance.",
    ),
    animation: animation(
      "Restrained movement with exact procedural handling, documentation and recovery beats.",
      [6, 10],
      "Working-room loops show staff and public activity without obscuring evidence or dialogue.",
      "Collection, bagging, logging and interview transitions remain discrete and reviewable.",
    ),
    interface: interfaceGrammar(
      "top-icon-bar",
      "icon-bar",
      ["icon-bar", "context"],
      0,
      false,
      "topic-ledger",
      "Evidence, equipment and notes open in modal case-file surfaces with explicit custody state.",
      "Procedure and case progress appear in authored reports and a caseboard, not a generic objective tracker.",
      "Walk, look, use, talk, collect, notes and system intents remain distinct and accountable.",
      false,
    ),
    puzzleGrammars: ["research-deduction", "topic-investigation", "environmental-state"],
    audio: audio(
      "Sparse location motifs and low-key tension never overpower dialogue or procedural feedback.",
      "Rain, traffic, fluorescent rooms, radios and paper establish place and working rhythm.",
      "Brief restrained cues mark evidence, contradiction, procedural warning and case progression.",
      "Camera, notebook, evidence bag and case-file sounds remain tactile and unglamorous.",
    ),
    splash: splashes.noir,
    showcase: showcase(
      "showcase.open-case",
      "Open Case",
      "Procedural crime investigation",
      "A city investigator must preserve a fragile evidence chain while a witness changes their account.",
      [
        "A rain-dark apartment scene with one protected entry, evidence zones and equipment staging.",
        "A controlled witness interview whose available questions depend on lawful evidence and prior answers.",
        "A precinct caseboard where custody, analysis and location progression remain inspectable.",
      ],
      ["procedure checks", "evidence custody", "case graph", "interrogation", "recoverable handling errors"],
    ),
    rule: "Correct procedure must clarify cause and consequence rather than acting as trivia.",
    prohibition: "Do not reward arbitrary checklist obedience without readable investigative purpose.",
    reviewQuestions: [
      "Can the player distinguish observation, collection, custody and analysis state?",
      "Does incorrect procedure explain the problem and preserve a bounded recovery path?",
      "Do evidence and testimony unlock case progress without a hidden arbitrary gate?",
    ],
  }),
] as const;
