import type { AdventureProductionProfile } from "./production-profile-types.js";
import {
  actors,
  animation,
  audio,
  interfaceGrammar,
  palette,
  profile,
  scene,
  showcase,
} from "./production-profile-factory.js";
import { productionProfileSplashes as splashes } from "./production-profile-splashes.js";

export const cinematicProductionProfiles: readonly AdventureProductionProfile[] = [
  profile({
    id: "cinematic-pulp-vga",
    label: "Cinematic Pulp VGA",
    family: "cinematic-pulp",
    summary: "Full-screen framing, multiple protagonists, relationship consequences and bespoke dossiers.",
    productionModes: ["cinematic-photocollage", "painted-pixel"],
    compositionModes: ["cinematic", "travel", "comic-panel"],
    pixelMotionPolicy: "camera-strict",
    palette: palette(
      256,
      ["#08090c", "#242733", "#5c4d43", "#8a664b", "#a13d37", "#d7c5a4"],
      "Use cinematic blacks with readable face and hand planes.",
      "Motivated highlights identify danger, intimacy and route information.",
      14,
    ),
    scene: scene(
      "Treat each screen as a directed shot with purposeful eyelines and cuts.",
      "Movement serves the shot without sacrificing interaction access.",
      "Relationship, danger and route choice lead every frame.",
      "Time, trust, resources and protagonist choice alter locations.",
    ),
    actors: actors(
      "Grounded figures with distinct posture, equipment and relationships.",
      [26, 48],
      "Full-screen or panel close-ups use directional light and restrained emotion.",
      "Blocking, eyelines and pauses communicate trust before text.",
    ),
    animation: animation(
      "Selective cinematic key poses, held close-ups and action inserts.",
      [6, 10],
      "Stillness and eye-line changes carry tension.",
      "Use panel, match and meanwhile cuts with deterministic closure.",
    ),
    interface: interfaceGrammar(
      "cinematic-dossier",
      "context",
      ["context", "two-button", "icon-bar"],
      0,
      false,
      "cinematic-close-up",
      "Character quick inventory plus dossier route and relationship state.",
      "Bespoke panels communicate time, cost and branch divergence.",
      "Minimal context changes; major choices happen in authored panels.",
      false,
    ),
    puzzleGrammars: ["relationship-branch", "multi-route", "hybrid-action", "inventory-chain"],
    audio: audio(
      "Cinematic motifs and character themes use restrained samples.",
      "Travel, city, weather and rooms continue across panels where useful.",
      "Route, danger and branch alerts use distinct signatures.",
      "Dossier, radio and map controls use tactile fictional sounds.",
    ),
    splash: splashes.kinetic,
    showcase: showcase(
      "showcase.jade-horizon",
      "Jade Horizon",
      "cinematic travel thriller",
      "A debt courier and disgraced pilot cross a collapsing route while every delay changes trust.",
      [
        "A rain-lit airstrip office with inventory and a time-cost choice.",
        "A river hotel where protagonist switching exposes different truths.",
        "A cliff railway sequence resolving route, fatigue and trust.",
      ],
      ["multiple protagonists", "relationships", "branch alerts", "travel dossier"],
    ),
    rule: "Keep character knowledge separate from audience-only events.",
    prohibition: "Do not make relationship values cosmetic or ending-only.",
    reviewQuestions: [
      "Does the frame communicate danger, relationship and route?",
      "Are branch alerts visible without spoiling alternatives?",
      "Does skipping a cinematic preserve canonical state?",
    ],
  }),
  profile({
    id: "neo-noir-lowres",
    label: "Neo-Noir Low-Resolution",
    family: "minimal-noir",
    summary: "Sparse rain-soaked pixels, restrained context interaction and multi-character investigation.",
    productionModes: ["painted-pixel", "graphic-cel"],
    compositionModes: ["cinematic", "stage"],
    palette: palette(
      64,
      ["#05070a", "#151c26", "#263b4a", "#4e5861", "#9a4c45", "#c6d0c7"],
      "Use a narrow cool-dark ramp with readable face, hand and evidence planes.",
      "Reserve one muted warm accent for identity, danger or evidence.",
      8,
    ),
    scene: scene(
      "Frame severe low-detail spaces with negative space and isolated action.",
      "Use a narrow unmistakable walk plane with no purposeless clutter.",
      "One actor, route question and evidence focus dominate each state.",
      "Identity, security, communication and weather changes stay obvious.",
    ),
    actors: actors(
      "Narrow coats, hard shoulders and distinct head profiles.",
      [22, 38],
      "Rare cropped close-ups use terminal light and minimal expression.",
      "Stillness, distance and guarded posture outrank broad gestures.",
    ),
    animation: animation(
      "Sparse held frames, measured walking and selective tool actions.",
      [6, 8],
      "Long still poses make small state changes significant.",
      "Use hard cuts and signal interruptions rather than smooth easing.",
    ),
    interface: interfaceGrammar(
      "minimal-context",
      "context",
      ["context", "two-button"],
      0,
      false,
      "minimal-caption",
      "A temporary strip or communicator with strong silhouettes.",
      "Short captions and quiet failure responses; no quest tracker.",
      "One restrained context cursor with explicit walk and exits.",
      false,
    ),
    puzzleGrammars: ["topic-investigation", "environmental-state", "hybrid-action"],
    audio: audio(
      "Low drones, sparse electric piano and small motif fragments.",
      "Rain, ventilation and distant transit carry location identity.",
      "Signals and memory cuts use filtered tones or silence.",
      "Communicator and terminal sounds remain dry and narrow-band.",
    ),
    splash: splashes.noir,
    showcase: showcase(
      "showcase.cold-meridian",
      "Cold Meridian",
      "science-fiction noir investigation",
      "Two estranged investigators discover that each is following the other's erased identity.",
      [
        "A rain platform with one terminal, distant figure and negative space.",
        "A rehabilitation ward using records and speaker-door dialogue puzzles.",
        "A maintenance bridge resolving both investigations in one controlled cut.",
      ],
      ["minimal context UI", "multiple investigators", "communicator research", "sparse palette"],
    ),
    rule: "Use negative space as deliberate composition, not unfinished art.",
    prohibition: "Do not add neon merely to signal science fiction.",
    reviewQuestions: [
      "Does the scene remain readable with most decoration removed?",
      "Is the warm accent reserved for identity, danger or evidence?",
      "Can the player distinguish what each protagonist knows?",
    ],
  }),
] as const;
