import {
  actors,
  animation,
  audio,
  interfaceGrammar,
  palette,
  profile,
  scene,
  showcase,
} from "./production-profile-factory.js";
import { productionProfileSplashes as splashes } from "./production-profile-splashes.js";
import type { AdventureProductionProfile } from "./production-profile-types.js";

export const cinematicProductionProfiles: readonly AdventureProductionProfile[] = [
  profile({
    id: "cinematic-pulp-vga",
    label: "Cinematic Pulp VGA",
    family: "cinematic-pulp",
    summary: "Full-screen framing, multiple protagonists, relationship consequences and bespoke dossiers.",
    productionModes: ["cinematic-photocollage", "painted-pixel"],
    compositionModes: ["cinematic", "travel", "comic-panel"],
    pixelMotionPolicy: "camera-strict",
    palette: palette(
      256,
      ["#08090c", "#242733", "#5c4d43", "#8a664b", "#a13d37", "#d7c5a4"],
      "Use cinematic blacks with readable face and hand planes.",
      "Motivated highlights identify danger, intimacy and route information.",
      14,
    ),
    scene: scene(
      "Treat each screen as a directed shot with purposeful eyelines and cuts.",
      "Movement serves the shot without sacrificing interaction access.",
      "Relationship, danger and route choice lead every frame.",
      "Time, trust, resources and protagonist choice alter locations.",
    ),
    actors: actors(
      "Grounded figures with distinct posture, equipment and relationships.",
      [26, 48],
      "Full-screen or panel close-ups use directional light and restrained emotion.",
      "Blocking, eyelines and pauses communicate trust before text.",
    ),
    animation: animation(
      "Selective cinematic key poses, held close-ups and action inserts.",
      [6, 10],
      "Stillness and eye-line changes carry tension.",
      "Use panel, match and meanwhile cuts with deterministic closure.",
    ),
    interface: interfaceGrammar(
      "cinematic-dossier",
      "context",
      ["context", "two-button", "icon-bar"],
      0,
      false,
      "cinematic-close-up",
      "Character quick inventory plus dossier route and relationship state.",
      "Bespoke panels communicate time, cost and branch divergence.",
      "Minimal context changes; major choices happen in authored panels.",
      false,
    ),
    puzzleGrammars: ["relationship-branch", "multi-route", "hybrid-action", "inventory-chain"],
    audio: audio(
      "Cinematic motifs and character themes use restrained samples.",
      "Travel, city, weather and rooms continue across panels where useful.",
      "Route, danger and branch alerts use distinct signatures.",
      "Dossier, radio and map controls use tactile fictional sounds.",
    ),
    splash: splashes.kinetic,
    showcase: showcase(
      "showcase.jade-horizon",
      "Jade Horizon",
      "cinematic travel thriller",
      "A debt courier and disgraced pilot cross a collapsing route while every delay changes trust.",
      [
        "A rain-lit airstrip office with inventory and a time-cost choice.",
        "A river hotel where protagonist switching exposes different truths.",
        "A cliff railway sequence resolving route, fatigue and trust.",
      ],
      ["multiple protagonists", "relationships", "branch alerts", "travel dossier"],
    ),
    rule: "Keep character knowledge separate from audience-only events.",
    prohibition: "Do not make relationship values cosmetic or ending-only.",
    reviewQuestions: [
      "Does the frame communicate danger, relationship and route?",
      "Are branch alerts visible without spoiling alternatives?",
      "Does skipping a cinematic preserve canonical state?",
    ],
  }),
  profile({
    id: "cinematic-handdrawn-conspiracy",
    label: "Cinematic Hand-Drawn Conspiracy",
    family: "cinematic-handdrawn",
    summary: "Hand-painted environments, clean cel characters, restrained context interaction and cinematic investigation for modern 2D adventure mysteries.",
    nativeSize: { width: 640, height: 360 },
    productionModes: ["graphic-cel", "storybook-gouache"],
    compositionModes: ["cinematic", "stage", "travel"],
    pixelMotionPolicy: "free",
    palette: {
      ...palette(
        256,
        ["#10141c", "#29313e", "#4f6572", "#8d735e", "#b85f52", "#e8d7bd", "#d9e5ea"],
        "Use deliberate cool/warm shadow families with clean cel separation; avoid muddy global grading.",
        "Highlights belong to named practical light, daylight or a motivated atmospheric source.",
        16,
      ),
      ditherRule: "Do not use VGA-style dithering as a default. Use clean authored colour fields, sparse texture and controlled painted gradients where the environment requires them.",
    },
    scene: scene(
      "Compose locations as cinematic hand-painted shots. Perspective may be cheated deliberately for story, mood and navigational readability, but floor/occlusion geometry must remain authored and testable.",
      "Characters inhabit broad readable action lanes inside richer painted environments; staging must preserve exits, clues and conversation anchors.",
      "Human figures, consequential evidence and architectural story clues dominate before decorative detail.",
      "Revisits reveal changed light, people, access and evidence while retaining recognisable environmental identity.",
    ),
    actors: actors(
      "Clean cel silhouettes with natural human proportion, expressive hands and distinct costume masses; anime-adjacent shape economy without copying a named production or artist.",
      [30, 56],
      "Conversation close-ups use controlled cel construction, restrained facial acting and shot-specific practical light rather than floating generic portraits.",
      "Performance uses purposeful holds, eye lines, anticipation and hand acting. Identity and construction remain locked to approved model sheets across every drawing.",
    ),
    animation: animation(
      "X-sheet-driven cel timing with authored key poses, holds, breakdowns and in-betweens; smoothness comes from planned exposure, not independent frame generation.",
      [8, 14],
      "Idle animation is sparse and character-specific: breath, gaze, weight transfer and contextual business rather than constant looping motion.",
      "Transitions preserve planted feet, contact points, silhouette and intent; action inserts may use explicit smears or held extremes only when authored in the X-sheet.",
    ),
    interface: interfaceGrammar(
      "minimal-context",
      "context",
      ["context", "two-button", "icon-bar"],
      0,
      false,
      "cinematic-close-up",
      "A compact object inventory with clean illustrative icons; conversation topics may use symbolic evidence/subject icons in dedicated dialogue presentation.",
      "Short contextual captions and conversation prompts; no permanent quest HUD.",
      "Subtle context cursor with explicit exits and inspect/talk/use intent; cursor art must not dominate the painted scene.",
      false,
    ),
    puzzleGrammars: ["research-deduction", "inventory-chain", "environmental-state", "topic-investigation", "multi-route"],
    audio: audio(
      "Orchestral/acoustic motifs with modern restraint; themes follow people, places and discoveries rather than playing continuously.",
      "City, interior, weather and architectural ambience carry depth and location identity underneath dialogue.",
      "Discoveries, travel and hard cutaways use short authored transitions rather than generic trailer impacts.",
      "Interface feedback is quiet, tactile and diegetically neutral.",
    ),
    splash: splashes.lantern,
    showcase: showcase(
      "showcase.ninth-reliquary",
      "The Ninth Reliquary",
      "cinematic hand-drawn conspiracy mystery",
      "A restoration researcher and freelance photojournalist trace a forged medieval reliquary through a modern European network whose ritual symbols conceal a financial crime.",
      [
        "A rain-cleared old-city square and café where environmental clues, conversation icons and a staged street incident establish the conspiracy without a quest marker.",
        "A conservation archive and hidden chapel with research topics, close-up object inspection, stairs/elevation, foreground occlusion and a temporary cinematic cutaway.",
        "A night train and mountain hospice sequence combining travel, character switching, evidence exchange and a hand-animated confrontation before returning to exploration.",
      ],
      [
        "hand-painted cinematic rooms",
        "model-sheet-locked cel animation",
        "topic investigation",
        "room cutaways",
        "multi-protagonist state",
        "cross-studio art review",
      ],
    ),
    rule: "Every accepted visual asset must retain governed source/review lineage; character animation must bind approved model-sheet and X-sheet evidence, and cut-out art must pass real-alpha admission before atlas use.",
    prohibition: "Do not imitate protected characters, frames or a named animation studio; do not accept fake checkerboard transparency, independently regenerated animation frames, generic anime faces, universal bloom or decorative camera drift.",
    reviewQuestions: [
      "Does the location feel authored as a cinematic place while remaining completely playable and readable?",
      "Do character drawings preserve identity, anchors, line/construction and exposure timing across the whole animation sequence?",
      "Can every accepted transparent asset prove real alpha and every creative revision show what changed, what was preserved and why it was accepted?",
    ],
  }),
  profile({
    id: "neo-noir-lowres",
    label: "Neo-Noir Low-Resolution",
    family: "minimal-noir",
    summary: "Sparse rain-soaked pixels, restrained context interaction and multi-character investigation.",
    productionModes: ["painted-pixel", "graphic-cel"],
    compositionModes: ["cinematic", "stage"],
    palette: palette(
      64,
      ["#05070a", "#151c26", "#263b4a", "#4e5861", "#9a4c45", "#c6d0c7"],
      "Use a narrow cool-dark ramp with readable face, hand and evidence planes.",
      "Reserve one muted warm accent for identity, danger or evidence.",
      8,
    ),
    scene: scene(
      "Frame severe low-detail spaces with negative space and isolated action.",
      "Use a narrow unmistakable walk plane with no purposeless clutter.",
      "One actor, route question and evidence focus dominate each state.",
      "Identity, security, communication and weather changes stay obvious.",
    ),
    actors: actors(
      "Narrow coats, hard shoulders and distinct head profiles.",
      [22, 38],
      "Rare cropped close-ups use terminal light and minimal expression.",
      "Stillness, distance and guarded posture outrank broad gestures.",
    ),
    animation: animation(
      "Sparse held frames, measured walking and selective tool actions.",
      [6, 8],
      "Long still poses make small state changes significant.",
      "Use hard cuts and signal interruptions rather than smooth easing.",
    ),
    interface: interfaceGrammar(
      "minimal-context",
      "context",
      ["context", "two-button"],
      0,
      false,
      "minimal-caption",
      "A temporary strip or communicator with strong silhouettes.",
      "Short captions and quiet failure responses; no quest tracker.",
      "One restrained context cursor with explicit walk and exits.",
      false,
    ),
    puzzleGrammars: ["topic-investigation", "environmental-state", "hybrid-action"],
    audio: audio(
      "Low drones, sparse electric piano and small motif fragments.",
      "Rain, ventilation and distant transit carry location identity.",
      "Signals and memory cuts use filtered tones or silence.",
      "Communicator and terminal sounds remain dry and narrow-band.",
    ),
    splash: splashes.noir,
    showcase: showcase(
      "showcase.cold-meridian",
      "Cold Meridian",
      "science-fiction noir investigation",
      "Two estranged investigators discover that each is following the other's erased identity.",
      [
        "A rain platform with one terminal, distant figure and negative space.",
        "A rehabilitation ward using records and speaker-door dialogue puzzles.",
        "A maintenance bridge resolving both investigations in one controlled cut.",
      ],
      ["minimal context UI", "multiple investigators", "communicator research", "sparse palette"],
    ),
    rule: "Use negative space as deliberate composition, not unfinished art.",
    prohibition: "Do not add neon merely to signal science fiction.",
    reviewQuestions: [
      "Does the scene remain readable with most decoration removed?",
      "Is the warm accent reserved for identity, danger or evidence?",
      "Can the player distinguish what each protagonist knows?",
    ],
  }),
] as const;
