import type {
  AdventureReferenceCapabilityCategory,
  AdventureReferenceCapabilityId,
  AdventureReferenceCapabilityRequirement,
  AdventureReferenceEvidenceKind,
} from "./reference-fidelity-types.js";

const evidence = (
  acceptedKinds: readonly AdventureReferenceEvidenceKind[],
  minimumItems: number,
  note: string,
) => ({ acceptedKinds, minimumItems, note });

export const capability = (
  id: AdventureReferenceCapabilityId,
  label: string,
  category: AdventureReferenceCapabilityCategory,
  critical: boolean,
  description: string,
  acceptedKinds: readonly AdventureReferenceEvidenceKind[],
  minimumItems = 1,
): AdventureReferenceCapabilityRequirement => ({
  id,
  label,
  category,
  critical,
  description,
  evidence: evidence(acceptedKinds, minimumItems, `Prove ${label.toLowerCase()} with retained evidence.`),
});

const contractEvidence = ["contract", "unit-test", "integration-test"] as const;
export const runtimeEvidence = ["integration-test", "deterministic-replay", "reference-trace"] as const;
const visualEvidence = ["screenshot", "video", "reference-trace", "manual-review"] as const;
const audioEvidence = ["audio-capture", "reference-trace", "manual-review"] as const;

export const commonCapabilities: readonly AdventureReferenceCapabilityRequirement[] = [
  capability(
    "native-320x200",
    "Native 320 × 200 canvas",
    "presentation",
    true,
    "Author and resolve gameplay at the native 320 by 200 logical canvas.",
    visualEvidence,
    2,
  ),
  capability(
    "indexed-256-colour",
    "Indexed 256-colour discipline",
    "presentation",
    true,
    "Enforce an indexed eight-bit colour budget with explicit room and interface reservations.",
    ["contract", "integration-test", "screenshot"],
    2,
  ),
  capability(
    "dos-pixel-aspect",
    "DOS pixel-aspect presentation",
    "presentation",
    false,
    "Review both source pixels and the intended four-by-three display presentation.",
    visualEvidence,
  ),
  capability(
    "integer-scaling",
    "Integer scaling",
    "presentation",
    true,
    "Present the native frame without fractional resampling.",
    contractEvidence,
  ),
  capability(
    "nearest-neighbour-sampling",
    "Nearest-neighbour sampling",
    "presentation",
    true,
    "Keep authored pixel clusters stable during presentation scaling.",
    contractEvidence,
  ),
  capability(
    "binary-sprite-alpha",
    "Binary sprite transparency",
    "presentation",
    true,
    "Use transparent-index or binary-alpha sprite edges without soft halos.",
    ["integration-test", "screenshot", "manual-review"],
    2,
  ),
  capability(
    "bitmap-typography",
    "Bitmap typography",
    "presentation",
    true,
    "Render dialogue, status and interface copy with native bitmap metrics.",
    ["integration-test", "screenshot"],
    2,
  ),
  capability(
    "fixed-logical-ticks",
    "Fixed logical ticks",
    "system",
    true,
    "Advance authored state and timing independently from monitor refresh cadence.",
    runtimeEvidence,
    2,
  ),
  capability(
    "walk-areas",
    "Walk-area navigation",
    "world",
    true,
    "Resolve actor movement through authored navigable regions and entrances.",
    runtimeEvidence,
    2,
  ),
  capability(
    "depth-scaling",
    "Depth and actor scaling",
    "world",
    true,
    "Apply authored baseline depth and scale while preserving actor readability.",
    ["integration-test", "reference-trace", "screenshot"],
    2,
  ),
  capability(
    "foreground-occlusion",
    "Foreground occlusion",
    "world",
    false,
    "Place actors behind authored foreground masks without hiding critical state.",
    visualEvidence,
  ),
  capability(
    "scene-transitions",
    "Authored scene transitions",
    "world",
    false,
    "Use deterministic fades, cuts and arrival staging appropriate to the title grammar.",
    ["integration-test", "reference-trace", "video"],
  ),
  capability(
    "semantic-cursors",
    "Semantic cursor feedback",
    "input",
    true,
    "Expose the current action and target state through deterministic cursor semantics.",
    ["integration-test", "screenshot", "reference-trace"],
    2,
  ),
  capability(
    "inventory-state",
    "Persistent inventory state",
    "system",
    true,
    "Preserve acquisition, consumption and object-use state through scenes and saves.",
    runtimeEvidence,
    2,
  ),
  capability(
    "dialogue-state",
    "Persistent dialogue state",
    "narrative",
    true,
    "Persist opened, exhausted and conditional dialogue choices deterministically.",
    runtimeEvidence,
    2,
  ),
  capability(
    "save-slot-ui",
    "Classic save-slot interface",
    "system",
    false,
    "Expose compatible saves, invalid saves and restart paths through the title grammar.",
    ["integration-test", "screenshot"],
  ),
  capability(
    "exact-save-restore",
    "Exact save and restore",
    "system",
    true,
    "Restore canonical story, scene, actor, inventory and subsystem state exactly.",
    runtimeEvidence,
    2,
  ),
  capability(
    "deterministic-replay",
    "Deterministic replay closure",
    "system",
    true,
    "Re-execute semantic input to the same final state and save fingerprint.",
    ["deterministic-replay", "integration-test"],
    2,
  ),
  capability(
    "terminal-outcome",
    "Governed terminal outcome",
    "narrative",
    true,
    "Resolve success, failure or death into an explicit recoverable lifecycle state.",
    runtimeEvidence,
    2,
  ),
  capability(
    "audio-channel-structure",
    "Period audio-channel structure",
    "audio",
    false,
    "Separate music, ambience, speech and interface cues with deterministic transitions.",
    audioEvidence,
  ),
  capability(
    "variant-specific-presentation",
    "Release-variant behaviour",
    "system",
    true,
    "Keep floppy and CD presentation, timing, speech and interface differences explicit.",
    ["contract", "integration-test", "reference-trace"],
    2,
  ),
  capability(
    "original-proof-content",
    "Original playable proof",
    "system",
    true,
    "Demonstrate the production grammar using only original EVAVO content and assets.",
    ["integration-test", "deterministic-replay", "screenshot", "manual-review"],
    3,
  ),
];
