import {
  audioMixManifestSchema,
  createDefaultAudioMixManifest,
} from "@evavo/adventure-audio";
import { parseAdventureProject } from "@evavo/adventure-project-schema";
import { studioProject } from "./fixture.js";

export const studioAudioProject = parseAdventureProject({
  ...studioProject,
  dialogues: [
    ...studioProject.dialogues,
    {
      id: "dialogue.night-clerk",
      name: "Night clerk interview",
      startNodeId: "dialogue-node.night-clerk.start",
      nodes: [
        {
          id: "dialogue-node.night-clerk.start",
          enterActions: [],
          lines: [
            {
              id: "dialogue-line.night-clerk.warning",
              speakerId: "actor.clerk",
              text: "The office has been closed since eleven.",
              animationState: "idle",
              durationTicks: 96,
              interruptible: true,
            },
          ],
          choices: [],
          exitActions: [],
        },
      ],
    },
  ],
  sequences: [
    ...studioProject.sequences,
    {
      id: "sequence.office.thunder",
      name: "Office thunder roll",
      mode: "ambient",
      durationTicks: 120,
      loop: false,
      blocking: false,
      savePolicy: "allowed",
      skip: {
        allowed: false,
        safeAfterTick: 0,
        completionActions: [],
      },
      tracks: [
        {
          id: "sequence-track.office.thunder.audio",
          kind: "audio",
          cues: [
            {
              kind: "sound",
              atTick: 18,
              assetId: "asset.audio.effect.thunder",
              bus: "effects",
              volume: 0.92,
              loop: false,
            },
          ],
        },
      ],
    },
  ],
  assets: [
    ...studioProject.assets,
    {
      id: "asset.audio.music.noir",
      path: "audio/music/noir-underscore.ogg",
      kind: "audio",
    },
    {
      id: "asset.audio.ambience.rain",
      path: "audio/ambience/rain-window.ogg",
      kind: "audio",
    },
    {
      id: "asset.audio.ambience.neon",
      path: "audio/ambience/neon-transformer.ogg",
      kind: "audio",
    },
    {
      id: "asset.audio.effect.thunder",
      path: "audio/effects/thunder-roll.ogg",
      kind: "audio",
    },
    {
      id: "asset.audio.speech.clerk-warning",
      path: "audio/speech/night-clerk-warning.ogg",
      kind: "audio",
    },
    {
      id: "asset.audio.interface.click",
      path: "audio/interface/verb-click.ogg",
      kind: "audio",
    },
  ],
});

export const studioAudioMix = audioMixManifestSchema.parse({
  ...createDefaultAudioMixManifest(studioAudioProject),
  cues: [
    {
      id: "audio-cue.music.noir",
      name: "Noir underscore",
      assetId: "asset.audio.music.noir",
      bus: "music",
      volume: 0.78,
      startOffsetMilliseconds: 0,
      fadeInTicks: 48,
      fadeOutTicks: 36,
      loop: {
        startMilliseconds: 1200,
        endMilliseconds: 32_400,
        crossfadeMilliseconds: 300,
      },
      polyphony: "restart",
      maxInstances: 1,
      priority: 20,
      interruptGroup: "score",
    },
    {
      id: "audio-cue.ambience.rain",
      name: "Rain against glass",
      assetId: "asset.audio.ambience.rain",
      bus: "ambience",
      volume: 0.74,
      startOffsetMilliseconds: 0,
      fadeInTicks: 24,
      fadeOutTicks: 24,
      loop: {
        startMilliseconds: 0,
        endMilliseconds: 28_000,
        crossfadeMilliseconds: 220,
      },
      polyphony: "restart",
      maxInstances: 1,
      priority: 10,
      interruptGroup: "weather",
    },
    {
      id: "audio-cue.ambience.neon",
      name: "Neon transformer hum",
      assetId: "asset.audio.ambience.neon",
      bus: "ambience",
      volume: 0.36,
      startOffsetMilliseconds: 0,
      fadeInTicks: 18,
      fadeOutTicks: 18,
      loop: {
        startMilliseconds: 300,
        endMilliseconds: 14_500,
        crossfadeMilliseconds: 120,
      },
      polyphony: "restart",
      maxInstances: 1,
      priority: 4,
      interruptGroup: "room-tone",
    },
    {
      id: "audio-cue.effect.thunder",
      name: "Thunder roll",
      assetId: "asset.audio.effect.thunder",
      bus: "effects",
      volume: 0.92,
      startOffsetMilliseconds: 0,
      fadeInTicks: 0,
      fadeOutTicks: 12,
      loop: null,
      polyphony: "overlap",
      maxInstances: 3,
      priority: 40,
      interruptGroup: null,
    },
    {
      id: "audio-cue.speech.clerk-warning",
      name: "Night clerk warning",
      assetId: "asset.audio.speech.clerk-warning",
      bus: "speech",
      volume: 1,
      startOffsetMilliseconds: 0,
      fadeInTicks: 1,
      fadeOutTicks: 2,
      loop: null,
      polyphony: "restart",
      maxInstances: 1,
      priority: 100,
      interruptGroup: "dialogue",
    },
    {
      id: "audio-cue.interface.click",
      name: "Interface click",
      assetId: "asset.audio.interface.click",
      bus: "interface",
      volume: 0.82,
      startOffsetMilliseconds: 0,
      fadeInTicks: 0,
      fadeOutTicks: 0,
      loop: null,
      polyphony: "overlap",
      maxInstances: 8,
      priority: 30,
      interruptGroup: null,
    },
  ],
  soundscapes: [
    {
      sceneId: "scene.office",
      layers: [
        {
          id: "audio-scene-layer.office.score",
          cueId: "audio-cue.music.noir",
          role: "music",
          startDelayTicks: 0,
          fadeInTicks: 48,
          fadeOutTicks: 36,
          restartPolicy: "continue",
        },
        {
          id: "audio-scene-layer.office.rain",
          cueId: "audio-cue.ambience.rain",
          role: "ambience",
          startDelayTicks: 0,
          fadeInTicks: 24,
          fadeOutTicks: 24,
          restartPolicy: "resume",
        },
      ],
    },
    {
      sceneId: "scene.alley",
      layers: [
        {
          id: "audio-scene-layer.alley.rain",
          cueId: "audio-cue.ambience.rain",
          role: "ambience",
          startDelayTicks: 0,
          fadeInTicks: 12,
          fadeOutTicks: 18,
          restartPolicy: "resume",
        },
        {
          id: "audio-scene-layer.alley.neon",
          cueId: "audio-cue.ambience.neon",
          role: "room-tone",
          startDelayTicks: 6,
          fadeInTicks: 18,
          fadeOutTicks: 18,
          restartPolicy: "continue",
        },
      ],
    },
  ],
  speechBindings: [
    {
      id: "audio-speech-binding.night-clerk.warning",
      dialogueLineId: "dialogue-line.night-clerk.warning",
      cueId: "audio-cue.speech.clerk-warning",
      leadInTicks: 2,
      tailTicks: 4,
      markers: [
        { atTick: 0, name: "mouth.rest" },
        { atTick: 8, name: "mouth.open" },
        { atTick: 24, name: "mouth.round" },
        { atTick: 52, name: "mouth.open" },
        { atTick: 88, name: "mouth.rest" },
      ],
    },
  ],
});
