import type { AdventurePlayFeelProfile } from "./types.js";
import { baseProfile, sharedInput, sharedPresentation } from "./preset-factory.js";

export const iconPlayFeelProfiles: readonly AdventurePlayFeelProfile[] = [
  baseProfile({
    id: "comic-snappy",
    label: "Comic Snappy",
    summary: "Fast responsive traversal, punchy turns, short reaction holds and crisp machine-comedy timing.",
    logicalTicksPerSecond: 60,
    movement: {
      topSpeedPixelsPerSecond: 59,
      accelerationPixelsPerSecondSquared: 520,
      decelerationPixelsPerSecondSquared: 620,
      minimumStartSpeedPixelsPerSecond: 18,
      arrivalSpeedPixelsPerSecond: 10,
      arrivalRadiusPixels: 0.3,
      turnSlowdownDegrees: 74,
      turnSpeedMultiplier: 0.82,
      quantization: "native-pixel",
      retargetPolicy: "replace-immediately",
    },
    animation: {
      phaseMode: "distance",
      pixelsPerWalkCycle: 17,
      footfallPhases: [0.16, 0.66],
      startPoseTicks: 1,
      turnPoseTicks: 1,
      arrivalPoseTicks: 2,
      actionAnticipationTicks: 2,
      actionRecoveryTicks: 4,
      minimumIdleTicks: 14,
    },
    camera: {
      mode: "fixed",
      deadZone: { left: 0.25, right: 0.75, top: 0.2, bottom: 0.8 },
      maximumSpeedPixelsPerSecond: 110,
      accelerationPixelsPerSecondSquared: 650,
      lookAheadPixels: 0,
      settleTicks: 1,
      quantization: "native-pixel",
    },
    input: { ...sharedInput, hoverCommitTicks: 0, commandBufferTicks: 12 },
    presentation: {
      ...sharedPresentation,
      renderInterpolation: "none",
      statusMinimumTicks: 24,
      sceneFadeOutTicks: 7,
      sceneDarkHoldTicks: 2,
      sceneFadeInTicks: 9,
    },
    authenticityRules: [
      "Make interaction response immediate while keeping story consequences tick-ordered.",
      "Time visual jokes through anticipation, impact and a readable held reaction.",
    ],
    prohibitedShortcuts: [
      "Do not use physics bounce or procedural overshoot as a substitute for comic poses.",
      "Do not accelerate the entire simulation to make traversal feel responsive.",
    ],
    reviewQuestions: [
      "Does a click acknowledge immediately even when the actor must approach?",
      "Are reaction holds deliberate rather than accidental frame stalls?",
    ],
  }),
  baseProfile({
    id: "gothic-measured",
    label: "Gothic Measured",
    summary:
      "Weighted investigation movement, restrained turns, long atmospheric " +
      "holds and controlled portrait timing.",
    logicalTicksPerSecond: 60,
    movement: {
      topSpeedPixelsPerSecond: 40,
      accelerationPixelsPerSecondSquared: 165,
      decelerationPixelsPerSecondSquared: 230,
      minimumStartSpeedPixelsPerSecond: 7,
      arrivalSpeedPixelsPerSecond: 5,
      arrivalRadiusPixels: 0.2,
      turnSlowdownDegrees: 48,
      turnSpeedMultiplier: 0.56,
      quantization: "native-pixel",
      retargetPolicy: "cancel-and-settle",
    },
    animation: {
      phaseMode: "distance",
      pixelsPerWalkCycle: 21,
      footfallPhases: [0.2, 0.7],
      startPoseTicks: 5,
      turnPoseTicks: 4,
      arrivalPoseTicks: 5,
      actionAnticipationTicks: 5,
      actionRecoveryTicks: 8,
      minimumIdleTicks: 40,
    },
    camera: {
      mode: "fixed",
      deadZone: { left: 0.26, right: 0.74, top: 0.2, bottom: 0.8 },
      maximumSpeedPixelsPerSecond: 66,
      accelerationPixelsPerSecondSquared: 210,
      lookAheadPixels: 0,
      settleTicks: 5,
      quantization: "native-pixel",
    },
    input: { ...sharedInput, hoverCommitTicks: 2, doubleActivationWindowTicks: 20 },
    presentation: {
      ...sharedPresentation,
      renderInterpolation: "none",
      statusMinimumTicks: 48,
      sceneFadeOutTicks: 18,
      sceneDarkHoldTicks: 8,
      sceneFadeInTicks: 22,
    },
    authenticityRules: [
      "Use stillness and controlled eyelines as part of investigative pacing.",
      "Keep evidence feedback and topic changes distinct from generic status text.",
    ],
    prohibitedShortcuts: [
      "Do not turn atmospheric pauses into unskippable input latency.",
      "Do not hide required clues behind low-contrast motion or transient text.",
    ],
    reviewQuestions: [
      "Does movement feel weighted without delaying the player's intent?",
      "Do pauses support suspicion, observation or consequence?",
    ],
  }),
] as const;
